### ISSUE TITLE
Oauth2 authentication issue with dev mode

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#1006]
### Bug description

I have an Oauth2 credential set up with Google and am trying to integrate it with my local wundergraph environment.
- I have a self-signed certificate for local https
- I have HOST rewrites set up on my device to redirect the domains to the correct IPs

When I start the WG application with `wunderctl up` and try the login flow, I get an error from the Google Oauth2 screen:
> Access blocked: This app’s request is invalid
> Error 400: redirect_uri_mismatch
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
> If you're the app developer, register the redirect URI in the Google Cloud Console.
> Request details: redirect_uri=http://api.my-local-url.com/auth/cookie/callback/google

Even though I have the `wundergraph.config.ts` setup as https, it sends me to http instead:
```
  ...
  authorizedRedirectUriRegexes: ["https://api.my-local-url.com/*"]
  ...
```

I've also verified that I have the `Authorized redirect URIs` in Google Credentials set up correctly as:
```
https://api.my-local-url.com/auth/cookie/callback/google
```

If I simply change `wunderctl up` to `wunderctl start`, then the authentication flow works. 

### How to reproduce

1. Generate a local self-signed certificate
2. Set up a demo UI and wundergraph backend with HTTPS
3. Add hosts file rewrites to point an example `dev.domain.com` to the UI and `api.domain.com` to wundergraph
4. Set up a Google Oauth2 credential flow with the correct redirects
5. Run `wunderctl up` and watch the workflow fail
6. Run `wunderctl start` and watch the workflow succeed

### Expected behavior

Wundergraph should not rewrite the redirect_uri as http when it is provided as https in the config.

### WunderGraph information

wundergraph.config.ts:
```
import {
    EnvironmentVariable,
    authProviders,
    configureWunderGraphApplication,
    introspect,
    templates
} from "@wundergraph/sdk"
import operations from "./wundergraph.operations"
import server from "./wundergraph.server"

const spaceX = introspect.graphql({
    apiNamespace: "spacex",
    url: "https://spacex-api.fly.dev/graphql/"
})

const hasura_user = introspect.graphql({
    apiNamespace: "user",
    url: new EnvironmentVariable("HASURA_GRAPHQL_HTTP_URL"),
    introspection: {
        pollingIntervalSeconds: 30
    },
    headers: (builder) => {
        builder.addStaticHeader("x-hasura-admin-secret", new EnvironmentVariable("HASURA_GRAPHQL_ADMIN_SECRET"))
        builder.addStaticHeader("x-hasura-role", "user")
        return builder
    }
})

const hasura_admin = introspect.graphql({
    apiNamespace: "admin",
    url: new EnvironmentVariable("HASURA_GRAPHQL_HTTP_URL"),
    introspection: {
        pollingIntervalSeconds: 30
    },
    headers: (builder) => {
        builder.addStaticHeader("x-hasura-admin-secret", new EnvironmentVariable("HASURA_GRAPHQL_ADMIN_SECRET"))
        builder.addStaticHeader("x-hasura-role", "admin")
        return builder
    }
})

// configureWunderGraph emits the configuration
configureWunderGraphApplication({
    apis: [hasura_user, spaceX, hasura_admin],
    server,
    operations: operations!,
    generate: {
        codeGenerators: [
            {
                templates: [
                    // use all the typescript react templates to generate a client
                    ...templates.typescript.all,
                    templates.typescript.operations,
                    templates.typescript.linkBuilder
                ]
            },
            {
                templates: [templates.typescript.client],
                path: "../../packages/generated-wundergraph"
            }
        ]
    },
    cors: {
        allowedOrigins: ["https://et2-dev.com/"] // process.env.NODE_ENV === "production" ? ["https://*"] : ["http://*"]
    },
    authentication: {
        cookieBased: {
            providers: [
                authProviders.google({
                    id: "google", // unique id for this provider
                    clientId: new EnvironmentVariable("GOOGLE_CLIENT_ID"),
                    clientSecret: new EnvironmentVariable("GOOGLE_CLIENT_SECRET")
                })
            ],
            secureCookieHashKey: new EnvironmentVariable("WG_SECURE_COOKIE_HASH_KEY"),
            secureCookieBlockKey: new EnvironmentVariable("WG_SECURE_COOKIE_BLOCK_KEY"),
            csrfTokenSecret: new EnvironmentVariable("WG_CSRF_TOKEN_SECRET"),
            authorizedRedirectUriRegexes: ["https://my-local-url.com/*", "https://api.my-local-url.com/*"]
        }
    },
    security: {
        enableGraphQLEndpoint: process.env.NODE_ENV !== "production"
    }
})

```

### Environment & setup

- OS: Windows 11 / Ubuntu 20 WSL2
- Database: PostgreSQL 15
- Node.js version: v18.16.0

### WunderCtl Version

```
Version: 0.154.0
Commit: 761d46c51cdb92da6fce745777bf4bf89e6c9bfe
Date: 2023-05-26T17:40:27Z
BuiltBy: ci
```

**Comment by jensneuse** [comment]
On the cmd `wunderctl up` (or start) can you try setting the flag `--disable-force-https-redirects`?

**Comment by AesSedai** [comment]
Hi @jensneuse, when I tried to add that flag it had this error:
> Error: unknown flag: --disable-force-https-redirects

**Comment by jensneuse** [comment]
I see, you're right. When using "start", we actually enforce https redirects, but allow you to disable it.
When using up, we default to http and you currently cannot change it:
https://github.com/wundergraph/wundergraph/blob/main/pkg/authentication/oidc.go#L173

I'll create a ticket internally. I think it would be best if we give the user more flexibility in configuring this per auth provider. WDYT?

**Comment by AesSedai** [comment]
Cool, that sounds like a good idea. Thanks for the quick response!

**Comment by AesSedai** [comment]
Still open.
