### ISSUE TITLE
Cookie based authentication with Lucia Auth

### ISSUE THREAD

**Issue by rnbokade** [wundergraph/wundergraph#1008]
@pilcrowOnPaper has created a really great library @pilcrowOnPaper/lucia which is simply awesome and one of the most flexible auth implementations from frameworks like Next.JS and sveltekit. It uses standard Apis for authentication and generate Cookies rather than jwts, allowing good session handling capabilities among other things.
I know NextAuth could be used because it was anyway generating jwt and thus could be handled well with token handler architecture of wundergraph server. But if we could somehow implement a cookie provider for Lucia, it would basically open doors for users to implement a lot of custom auth flows themselves according to their application and compliance needs (e.g. some compliances require single concurrent sessions, which could only be implemented by such flexible implementations) while still being able to use wunderful authentication aware data fetching capabilities of wundergraph

**Comment by jensneuse** [comment]
I have good news for you. We are currently designing an interface that allows everyone to build any http based integration, including auth, they want. It will be very flexible.
