### ISSUE TITLE
Feature: Add "fromClaim" functionality to graphql upstream headers builder

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#1010]
## Problem
I have cookie-based auth configured and use a Hasura graphql data source, and authorization in Hasura from a backend server on behalf of a user relies on a few other special headers attached to the request. This isn't an issue if Hasura is also the authentication provider, but I'm using WG for Oauth2 so Hasura doesn't have the config to parse the auth cookie.

This means that correctly accessing things in a Hasura request with authorization needs the admin secret to WG can make the request, and at minimum the `x-hasura-role` and `x-hasura-user`-id header has to be set. I have a couple of extra headers that are specific to my application permissions schema (`x-hasura-realm-id`, `x-hasura-character-id`) as well.

So, if I have a graphql operation I call from the client it fails because the request is missing the client-specific upstream headers. That can insecurely be worked around in the UI by calling `client.setExtraHeaders` and populating those values from the cookie custom claims and adding `builder.addClientRequestHeader("x-hasura-role", "x-hasura-role"), ...` but that means any client could set the request headers to whatever they want.

## Suggested solution

Expand the graphql upstream header builder to include a `fromClaim` feature that can populate a header from a claim. Example implementation code:
```
builder.addClientRequestHeaderFromClaim(upstreamRequestHeaderName, claimName)
```

```
headers: (builder) => {
    builder.addStaticHeader("x-hasura-admin-secret", new EnvironmentVariable("HASURA_GRAPHQL_ADMIN_SECRET"))
    builder.addClientRequestHeaderFromClaim("x-rasura-realm-id", "realmId")
    builder.addClientRequestHeaderFromClaim("x-hasura-character-id", "charId")
    builder.addClientRequestHeaderFromClaim("x-hasura-user-Id", "userId")
    builder.addClientRequestHeaderFromClaim("x-hasura-role", "role")
    return builder
}

configureWunderGraphApplication({
  ...
      authentication: {
        customClaims: {
            role: {
                jsonPath: "hasura.role",
                type: "string"
            },
            userId: {
                jsonPath: "hasura.userId",
                type: "string"
            },
            charId: {
                jsonPath: "hasura.charId",
                type: "string"
            },
            realmId: {
                jsonPath: "hasura.realmId",
                type: "string"
            }
        }
        ...
      }
  ...
})
```

## Alternatives

Maybe this is possible with operation hook pre-resolve to inject the headers? But that would be required for every single client UI operation and that's a lot of work.

**Comment by leoalves** [comment]
There is a global hook where you can decrypt the cookie and add headers you want to forward to Hasura.
This example has a global hook for subscriptions but API exposes an http protocol as well

https://github.com/wundergraph/wundergraph/tree/main/examples/graphql-subscriptions-hooks

**Comment by AesSedai** [comment]
Thanks for the pointer, it turns out the `onConnectionInit` hook doesn't let you change the header for the WS connections (I think that's what I saw at least), changing the `httpTransport.onOriginRequest` hook for all operations did however.

That may work as a workaround for now, but I think adding a specific builder API would be a better solution overall.

**Comment by AesSedai** [comment]
Still open.

**Comment by Pagebakers** [comment]
@AesSedai I've looked into this, while I really like the idea of addHeadersFromClaim, it will be very hard to implement, because the graphql engine isn't aware of the user claims.The only way is to forward them as headers using hooks.

You can return the headers in onConnectionInit:

```ts
onConnectionInit({user}) {
   return {
      "x-user-id": user.userId
   }
}
```
