### ISSUE TITLE
Bug: Very large schemas cause configuration init issues

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#1020]
### Bug description

I pointed WG at my postgres database (~65 tables, lots of relationships) and it near immediately barfed in a few places with a `RangeError: Invalid string length` error at a few of the JSON.stringify locations in the `configureWunderGraphApplication` code path.

After some googling, it looks like that error is related to v8 running out of memory (?) or otherwise faulting with a too-large input object to stringify.

Taking a look at the db introspection file at generated/introspection/database shows it is 8.2Mb.

I have the code on a forked branch, [diff](https://github.com/wundergraph/wundergraph/compare/main...AesSedai:stringify-fixes?expand=1).

I'm not sure if there are other areas where this is also an issue, but those fixes allowed my postgres schema to be successfully parsed and allowed WG to start up.

### How to reproduce

Make a large schema (50+ tables with lots of relationships) in postgres and try to compose it into Wundergraph.

Private repro available here: https://github.com/AesSedai/wundergraph-stringify-example

### Expected behavior

Wundergraph should compile and run successfully.

### WunderGraph information

N/A

### Environment & setup

- OS: Windows 11 / WSL2 Ubuntu 20
- Database: PostgreSQL
- Node.js version: Node 18

### WunderCtl Version

```
0.154.0
```

**Comment by aref-mehran** [comment]
hi dear @AesSedai  have you solved it?

**Comment by AesSedai** [comment]
@aref-mehran No, I didn't solve it. I moved on to a different project for now.
