### ISSUE TITLE
Support Pooled DB Connections

### ISSUE THREAD

**Issue by HXavS** [wundergraph/wundergraph#1040]
## Problem

Failed to Parse Prisma config with pooled connection
`...@ep-####-####-######-pooler.us-west-2.aws.neon.tech/######?pgbouncer=true&connect_timeout=10`

See's prisma config as invalid
```
directUrl         = env("DIRECT_URL")
shadowDatabaseUrl = env("SHADOW_URL")
```

## Suggested solution

Add support for pooled connection

**Comment by fiam** [comment]
Closing due to lack of information
