### ISSUE TITLE
Reduce storage for wundergraph generated config, current amplification is 1000x+ when generated from Prisma

### ISSUE THREAD

**Issue by rverma-nsl** [wundergraph/wundergraph#1053]
## Problem
While consuming a Prisma file of around 140Kb with 1500 schemas, the wundergraph config is generated to consume 900GB of disk space. Not only this makes extravagant use of disk and heap memory, but it also makes the queries very slow.

## Suggested solution
These are just some of the suggestions, more can be added by the community
1. Introduced schema with dynamic operations
2. Store the non-repeating data fragments in a KV store and use the same for loading operations
3. Expose an entity annotation to mark what operations we want to generate out of the box.

## Alternatives
Not aware

## Additional context
We should create an RFC for this, this may have a bigger impact on the way wundergraph handles Graphql. Also, I am not sure how these are optimized in scenarios of schema stitching or Graphql mesh

**Comment by fiam** [comment]
This should have been improved by a significant margin in https://github.com/wundergraph/wundergraph/pull/1070, which was first available in SDK 0.166.1. Could you please give it a try and let us know? Thanks!

**Comment by fiam** [comment]
Considering this as fixed by #1070. If that's not the case, please let us know and we'll reopen it. Thanks!
