### ISSUE TITLE
Support for Qwik

### ISSUE THREAD

**Issue by shiftlabs1** [wundergraph/wundergraph#1074]
## Problem
I wish to find out if Wundergraph has support for Qwik framework. I see support for other frameworks that are framework specific and wish to know if there are any plans for Qwik. We are starting a new project and plan to go with Qwik and genQL, but are exploring WunderGraph for the graphQL backend (Hasura as the alternative).

**Comment by jensneuse** [comment]
There's no specific Qwik integration currently available. You can use a pure typescript client though if that's enough.

**Comment by shiftlabs1** [comment]
The pure typescript client should do . Thanks

**Comment by jensneuse** [comment]
> The pure typescript client should do . Thanks 
> 

Ok cool. Let me know if we can do better than that.
