### ISSUE TITLE
Allow colocating operations with code like relay, graphql-codegen client-preset

### ISSUE THREAD

**Issue by osdiab** [wundergraph/wundergraph#1075]
## Problem

graphql-codegen’s client-preset has a pretty neat way of defining operations directly in your code with gql fragments, that basically results in it being much easier to prevent over fetching because the values fetched are right next to where they would be used.

But WunderGraph wants me to put all the operations and fragments in the .wundergraph folder, which basically makes that impossible.

## Suggested solution

would be cool if I could still reap the benefits of colocating queries with usage while using WunderGraph.

One way would be to add a flag that enables the following behavior:

- define queries and fragments via a template literal in code
- WunderGraph scans the code for these literals, generating types (including fragment types we can use to type component parameters)

## Alternatives

I am currently evaluating WunderGraph - Is there a way to go with graphql-codegen instead of WunderGraph’s own operation solution? I’m guessing not

**Comment by jensneuse** [comment]
Here's an example with the Relay integration that does exactly what you're looking for: https://github.com/wundergraph/wundergraph/tree/main/examples/nextjs-relay-todos

The Delay compiler composes all Fragments and operations and "prints" them into the WunderGraph directory. That makes WunderGraph compile all operations to JSON RPC. We've then built an adapter for the WunderGraph RPC protocol and the Relay client, so they work together nicely.

The same approach would be possible with other clients and tools similar to Relay.

**Comment by osdiab** [comment]
Oh sweet, thanks for the pointer! Looks promising.
