### ISSUE TITLE
Hooks can't be minified

### ISSUE THREAD

**Issue by jantimon** [wundergraph/wundergraph#108]
### Bug description

Hooks are used a lot in the codebase.  

Relay and ApolloGraph (while having other disadvantages) generate a hook for every query e.g. `useUserInfo`:

```js
const {data} = useUserInfoQuery()
```

Which minifies to:

```js
d=e().data,
```

Unfortunately `wundergraph` uses properties which can't be minified:

```js
const {data} = `useQuery.UserInfo().body`;
```

Which minifies to almost twice as much code:

```js
d=e.UserInfo().body,
```

This codes needs to be transfered, decompressed and parsed and has a small negative impact on performance.

It would be cool to further optimize Wundergraphs API to allow even smaller javascript bundles.

**Comment by Pagebakers** [comment]
@jantimon I've opened a discussion recently to propose similar optimizations, love to hear your feedback.

https://github.com/wundergraph/wundergraph/discussions/80

**Comment by jantimon** [comment]
Thanks for the hint - I wrote some words in the discussion :)

Please let me know if it's reasonable.

I'll close this bug :)
