### ISSUE TITLE
TypeScript ORM requires double WHERE syntax with Prisma data source

### ISSUE THREAD

**Issue by s1monj** [wundergraph/wundergraph#1082]
## Problem

With a Prisma data source eg:
```
const prismaDataSource = introspect.prisma({
  apiNamespace: "prisma",
  prismaFilePath: "../prisma/schema.prisma",
});
```

Current syntax required:
```
export default createOperation.query({
  handler: async (req) => {
    const value = await req.graph
      .from("prisma")
      .query("findFirstX")
      .select("id")
      .where({ where: { id: { equals: 100 } } })
      .exec();
    return {
      assets,
    };
  },
});
```

## Suggested solution

Preferred syntax is to remove one where:
```
export default createOperation.query({
  handler: async (req) => {
    const value = await req.graph
      .from("prisma")
      .query("findFirstX")
      .select("id")
      .where({ id: { equals: 100 } })
      .exec();
    return {
      assets,
    };
  },
});
```

**Comment by WcaleNieWolny** [comment]
@Aditay2002 Are you working on this? I would really attempt this. Let me know if you need my help

**Comment by nicktrn** [comment]
@Slickstef11 The intended outcome is not entirely clear here.

What about some of the other exposed Prisma APIs, e.g. orderBy, skip, take, etc?

![prisma-where](https://github.com/wundergraph/wundergraph/assets/55853254/f5077f80-fe70-4fdf-a27c-d64b9ecf358e)

"Removing one where" also means creating potential clashes between those and existing field names.

**Comment by s1monj** [comment]
> @Slickstef11 The intended outcome is not entirely clear here.
> 
> What about some of the other exposed Prisma APIs, e.g. orderBy, skip, take, etc?
> 
> ![prisma-where](https://user-images.githubusercontent.com/55853254/260156791-f5077f80-fe70-4fdf-a27c-d64b9ecf358e.png)
> 
> "Removing one where" also means creating potential clashes between those and existing field names.

Agreed - from the DX side of things, it doesn't make sense to be passing `orderBy` into an ORM `where` function, but I'm not sure if the intention is to be using Prisma seamlessly from an ORM wrapper, or to pass prisma-specific parameters through, in which case a better name for "where" would be something like "params".

**Comment by nicktrn** [comment]
Creating a universal interface like this certainly brings several design challenges with it. Reminds me of the old xkcd strip about standards.

**Comment by WcaleNieWolny** [comment]
I believe the intention is for the `where` function to work as a filter. In the docs we can see an example of that. (`.where({ id: 'abc' })`) so I believe we have 2 options.

1:
 - Strip the `where` funciton in a way that would take `UserWhereInput` instead of the `findFistUser` object (Essentially removing all of the fields that are not related to the `where` fn) 
 - Rename the `where` fn to `filter` or `combinedFilter` to make migration from this change easier
 
 2:
  - Rename the `where` fn to `filter` which is a more suitable name for this as it can not only do `where` but also limit the number of entries if `findManyUser` is used

**Comment by Pagebakers** [comment]
We cannot simply remove where here, since the prisma query also accepts other arguments. The only way forward to rename the where method of the ORM to prevent any confusion. Maybe `input` or `variables`.

```ts
    const value = await req.graph
      .from("prisma")
      .query("findFirstX")
      .select("id")
      .variables({ where: { id: { equals: 100 } } })
      .exec();
```
