### ISSUE TITLE
TypeScript ORM - include nested objects without manually selecting all scalar field names

### ISSUE THREAD

**Issue by s1monj** [wundergraph/wundergraph#1085]
## Problem
We have some tables with 20+ columns
> As a convenience the ORM will select all scalar fields on an object type.

so this is great. But if I want to include the nested/related objects in addition to all scalar fields above, it appears the only way to do this is to type out all of the top-level scaler field names.

From the example:
```
const result = await graph
  .from('people')
  .query('user')
  .select('id', 'firstName', 'friends.firstName', 'friends.lastName')
  .where({ id: 'abc', friends: { limit: 1 } })
  .exec();
```

- If I want to get all of the user fields, I can just omit the select() function
- If I want to get all of the friends fields, I can just add .select(friends)
- But if I want to include all of the user fields AND all of the friends fields, I think I need to write out all the user fields one-by-one, eg: `.select(id, first_name, last_name, ph, email, ..., friends)`

With 20+ columns this will get tedious
Prisma has a function called include that allows for this: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#include

## Suggested solution

Either allow for wildcard selectors, eg `.select('user.*','friends.*')` or implement `inclue()` function similar to Prisma

**Comment by shiftlabs1** [comment]
I was going to ask about this alongside snake or Pascal case to camelCase options in the Orm and generated client. genQl client has this too with ...everything

**Comment by shiftlabs1** [comment]
please reopen . This is very important
