### ISSUE TITLE
Add config of custom paths for watcher in dev

### ISSUE THREAD

**Issue by s1monj** [wundergraph/wundergraph#1088]
## Problem

Hot reloading works well for files changed in `./.wundergraph/*` when using `"start": "wunderctl up --logs"` in dev.

However, when migrating an existing codebase to WG or with complex logic that uses a directory hierarchy outside of `./.wundergraph`, it would be nice to add additional paths to watcher for hot reloading, eg `./src/support/utils.ts`

## Suggested solution

Allow addition of custom paths to watcher via configuration in `wundergraph.config.ts`

## Alternatives

Use nodemon to restart the server (but this may get slow as we increase our number of operations)

**Comment by Slickstef11** [comment]
@s1monj I like the suggestion. Will bring it up this week
