### ISSUE TITLE
[Issue]: OpenID Connect Not working 

### ISSUE THREAD

**Issue by raman-exiliensoft** [wundergraph/wundergraph#1095]
### Description

We are using OpenID Connect as below:

authentication: {
  cookieBased: {
    providers: [
      authProviders.openIDConnect({
        id: 'oidc', // you have to choose this ID
        issuer: new EnvironmentVariable('OIDC_ISSUER'),
        clientId: new EnvironmentVariable('OIDC_CLIENT_ID'),
        clientSecret: new EnvironmentVariable('OIDC_CLIENT_SECRET'),
      }),
    ];
  }
}

 but we are getting the following error after authenticated from ODIC povider:

ERROR OpenIDConnectCookieHandler postAuthentication failed {"component": "@wundergraph/node", "error": "could not encode user data: securecookie: the value is too long"}

![image](https://github.com/wundergraph/wundergraph/assets/114407340/ce609716-e1af-4f52-a84b-1eb51e43eb52)

Can you please check it out?

Thanks

### Reproduction

Just use openIDConnect instead of auth provider

**Comment by Slickstef11** [comment]
@raman-exiliensoft we're taking a look

**Comment by raman-exiliensoft** [comment]
@Slickstef11 Thanks for taking a look. Please tell us when we can expect it to be fixed.

**Comment by fiam** [comment]
@raman-exiliensoft This happens because we store the user profile in the cookie, which we limit to 4K to maximize browser compatibility. Could you let us know what are you storing in the user profile that causes it to overflow that limit? Thanks!

**Comment by raman-exiliensoft** [comment]
@fiam We are using Frontegg Auth as an openIdConnect in wundergraph and we are getting the following data from Frontegg Auth which we are logging in postAuthentication hook 

Please review the response after authentication.

[Frontegg-response.txt](https://github.com/wundergraph/wundergraph/files/11935009/Frontegg-response.txt)

Can you please let us how we can limit response under 4K?

Thanks

**Comment by raman-exiliensoft** [comment]
@fiam @Slickstef11 We have checked Google Social Login is also throwing same error "could not encode user data: securecookie: the value is too long"  with the default Auth0 provider so please check and look into it. 

Other login with password, Github and Linkdine are working fine

**Comment by fiam** [comment]
@raman-exiliensoft That's not something we can fix in the framework because it's a limit imposed by web browsers. A workaround we can suggest is using the `mutatingPostAuthentication()` hook to store some of the profile somewhere else and make sure that what is stored in the User object is 4K or less.
