### ISSUE TITLE
[Issue]: Idtokens not expiring on Nextjs application even set id Token Expiration in Auth0

### ISSUE THREAD

**Issue by raman-exiliensoft** [wundergraph/wundergraph#1102]
### Description

We are using Auth0 in Nextjs application with Wundergrapgh as a token handler. We have set IdToken and refresh token Expiration in Auth0 but still id Token is not refreshing on expiration.

Can you please provide an example of how to invalidate the session and test it?

Thanks
Raman Kumar

### Reproduction

Set ID Token and Refresh Token Expiration in Auth0 application settings and check Id Token in wundergarph after expiration

**Comment by fiam** [comment]
Hello @raman-exiliensoft. WunderGraph does support setting and expiration for the user session in the `postAuthentication()` hook. You can use a custom hook to make the session expire at the same time as the token by setting the `expires` field in the `User`. You can see an example [here](https://github.com/wundergraph/wundergraph/blob/2da215501862318dc9edd6c8d459965f3f1c7746/packages/testsuite/apps/auth/.wundergraph/wundergraph.server.ts#L40)

**Comment by jimmiebtlr** [comment]
I may be having a separate issue actually, will look further and maybe post a separate issue.  Currently logging out the user, I'm seeing an expiration of tomorrow, but fetchUser is returning 'User is not authenticated'.
