### ISSUE TITLE
Add validation to file uploads

### ISSUE THREAD

**Issue by deslee** [wundergraph/wundergraph#112]
## Problem

Currently file uploads cannot be restricted by size or mimetype

## Suggested solution

A configuration in s3UploadProvider could look like:

```
allowedUploads: [
	{
		mimeTypes: ["image/*", "audio/*"],
		sizeLimit: '200M',
		requiredRoles: ['verified']
	},
	{
		mimeTypes: ['text/*'],
		sizeLimit: '5M',
		requiredRoles: []
	},
	{
		mimeTypes: ['video/*', 'audio/*'],
		sizeLimit: '2G',
		requiredRoles: ['paidsubscriber']
	}
]
```

with the default value being
```
allowedUploads: [
	{
		mimeTypes: ['*'],
		sizeLimit: null,
		requiredRoles: []
	},
]
```

## Alternatives

Using typescript middleware to validate / authorize uploads is also another option, but less efficient

**Comment by jensneuse** [comment]
If a user is uploading audio, how should we determine which rules to apply?
required roles that would apply are either verified or paidsubscriber

How about implementing a typescript hook to determine allowed mimetypes and upload size limit?
e.g.

```typescript
interface limit {
  mimeTypes: string[];
  sizeLimit: string;
}

{
  allowedUploads: (user: User) :limit => { 
    return {mimeTypes: ['*'],sizeLimit: null}
  }
}
```

With this, depending on the user info, roles, etc.. (all info is contained in the user Object), you can determine with a TS function what upload rules should apply for the user.
