### ISSUE TITLE
null values in body are not passed through to graphql backend

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#114]
The Wundergraph operation looks like this:
```
mutation someUpdate($id: Int!, $name: String, $description: String, $icon: URL, $image: URL, $labels: [String!]) {
    object: someUpdate(id: $id, name: $name, description: $description, icon: $icon, image: $image, labels: $labels)
    {
        id
    }
}
```
I have the semantics that we can clear a value by sending an update with a null value. 
This is different to sending an update when some values are not set, which means don't change the values not included in the call.

For example, in the below call, I want to clear the existing "name" attribute on the object.
```
--- ClientRequest start ---

POST /api/main/operations/someUpdate HTTP/1.1
Host: localhost:9991
Accept: */*
Content-Length: 23
Content-Type: application/json
User-Agent: curl/7.68.0

{"id": 0, "name": null}



--- ClientRequest end ---



--- DebugTransport ---

Request:

POST / HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: application/json

{"variables":{"id":0},"query":"mutation($id: Int!, $name: String, $description: String, $icon: URL, $image: URL, $labels: [String!]){object: someUpdate(id: $id, name: $name, description: $description, icon: $icon, image: $image, labels: $labels){id}}"}

Duration: 121 ms

Response:

HTTP/1.1 200 OK
Content-Length: 28
Content-Type: application/json
Date: Fri, 05 Aug 2022 04:52:27 GMT
Server: uvicorn

{"data":{"object":{"id":0}}}

--- DebugTransport
```

You can see by the above, the Wundergraph server removes the "name" attribute, as it is null. If I set it to something else, it works ok.

The desired behaviour is for the wundergraph server to pass through null-valued arguments.

**Comment by jensneuse** [comment]
Thanks for reporting. We've got people who wanted to have the exact opposite behaviour. I guess we should make this configurable. Do you think this need to have granular configuration or could it be just at the datasource level? E.g. switch it on or off via boolean config param for the whole origin.

**Comment by greemo** [comment]
Hi Jens, thanks for the quick response.

In GraphQL, one can have different semantics for non-inclusion vs inclusion as null. Therefore I believe the default should be to pass nulls through. Otherwise an intentional feature of GraphQL backends is not available through Wundergraph.

I see this filtering null values as an additional filtering feature, rather than the way the system should behave by default.

If someone wishes to have this filtering nulls behaviour, and they want it in the Go codebase for performance reasons, rather than a hook, I can see the value in that. I imagine enabling the filter for the entire datasource would be sufficient. I would do it wherever it's easiest and most performant.

**Comment by jensneuse** [comment]
Sounds reasonable to me, although the reason is not performance. In some cases, you don't want to send nulls because the server handles them differently than empty fields, e.g. in a patch.

**Comment by greemo** [comment]
Yes, this is the reason I meant.
Regarding performance, I meant doing the filtering in the Go code instead of in the Node hooks, where it could also be done. :)

**Comment by jensneuse** [comment]
Hey @spetrunin nice find :-)
