### ISSUE TITLE
onOriginRequest not executed

### ISSUE THREAD

**Issue by brampurnot** [wundergraph/wundergraph#1140]
### Description

Hello!

I just started with Wundergraph so this might be a miss or misunderstanding on my side. We are trying to replace our Apollo Federated supergraph by Wundergraph. We have a very specific requirement for signing requests so we are implementing the "onOriginRequest" hook. We have the "enableForAllOperations" attribute set to true but for some reason, the hook is never executed. 

### Reproduction

NodeJS 18. Not yet deployed in K8S. Just testing it out locally. Installed via yarn:
```
  "dependencies": {
    "@wundergraph/nextjs": "^0.12.2",
    "@wundergraph/orm": "^0.2.0",
    "@wundergraph/sdk": "^0.158.1"
  },
```

Here is our server implementation:
```
import { configureWunderGraphServer } from '@wundergraph/sdk/server';
import type { HooksConfig } from './generated/wundergraph.hooks';
import type { InternalClient } from './generated/wundergraph.internal.client';

export default configureWunderGraphServer<HooksConfig, InternalClient>(() => ({
	hooks: {
		global: {
			httpTransport: {
			  onOriginRequest: {
				enableForAllOperations: true, // Trigger this hook for all operations
				hook: async ({ request }) => {
					request.headers.set('internal', 'true');
					request.headers.set('test', 'lala');
					console.log('----- onOriginRequest', request.headers);
					return request;
				},
			  },
			},
		},
		queries: {
		},
		mutations: {},
	},
	graphqlServers: [],
}));

```

**Comment by fiam** [comment]
Hello @brampurnot. Your configuration is correct but hooks only run when the query is triggered by a WunderGraph operation, not by a GraphQL query to `http://localhost:9991/graphql`. However, we have a new feature almost ready that allows you to manipulate every request, including the ones spawning from direct GraphQL queries. If you'd like to take a look, it's available in #1124

**Comment by brampurnot** [comment]
Awesome! Thanks for the quick turnaround! Much appreciated

**Comment by Slickstef11** [comment]
Hey @brampurnot just sent you a email to the email on your profile! 

Looking forward to connecting!

**Comment by brampurnot** [comment]
@fiam, I noticed this was released in the 0.170.0 release. Is there any documentation you can point me to? 

Thanks,
Bram

**Comment by fiam** [comment]
Hello @brampurnot - Documentation on this feature is a bit sparse for the moment, but we have a [README](https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/advanced-hooks/README.md) with the basic setup as well as some examples.

**Comment by fiam** [comment]
@brampurnot We're happy to help. For the time being there's no shorthand method. You would need to explicitly list all data sources and query types that you want to match. We'll open an internal issue to discuss adding it.

**Comment by brampurnot** [comment]
Ok no worries. I can live with that. And does this work for apollo federated supergraphs too? 

We have this defined:
`const federatedApi = introspect.federation({
  apiNamespace: "federated",
  upstreams: [
      {
        name: 'generic',
        url: "http://127.0.0.1:8000/generic",
        headers: (builder) => builder.addStaticHeader('internal', 'true'),
      },
...`

And then we are trying to match it like this:
`const transport = dynamicTransport({
	match: [
	  {
		operationType: 'query',
		datasources: ['federated']
	  },
	],`

However it still doesn't seem to be triggered. Not sure if I'm missing something here. 

Bram
