### ISSUE TITLE
Query Fragments Support for Server Driven UI architecture

### ISSUE THREAD

**Issue by matt-cochran** [wundergraph/wundergraph#115]
## Problem

My aim is to build [SDUI](https://medium.com/airbnb-engineering/a-deep-dive-into-airbnbs-server-driven-ui-system-842244c5f5) apps.  

Server-driven UI composition means I have data structures that are reused frequently and bound to explicit components (...from extremely simple and fine-grained utility components that are composed into larger, more complex and coarse-grained feature-level components).  

Example 1: A 'FormattableString' type that includes a value along with the underlying format ('markdown', 'plain-text', 'html', etc). I bind this micro-data-structure a single front-end component for rendering, and another one for editing.
Example 2: A 'comment' data structure paired with a component that can be applied to different entities (that uses the 'FormattableString' component)  

Not having fragment support poses two primary development and maintenance problems with a SDUI architecture:
1) Operations are overly verbose and a challenge to read/write/maintain
2) Schema changes are painful because of the cascades across all queries (and multiple places in each query)

Currently, Wundergraph (without fragment support) means a sustainable/composable SDUI architecture is not really possible.  This is because every detailed piece of data needed for each instance of a reusable component has to be re-re-restated in the query… which is especially tedious with the more fine-grained UI building blocks.

Without fragment support, I also see significant maintenance challenges as my apps mature, and my code base grows …. I love what you are doing with WunderGraph and think it is a brilliant approach (and the right one).  Unfortunately, I may have to go another route for a SDUI front-end (which would be a shame, because everything else in WunderGraph is truly awesome).

## Suggested solution

I would like to see first-class support of fragments.

## Alternatives

My challenge is more of a **maintenance and development experience** concern, rather than a **functional** one.

I would be completely satisfied if we just supported the *fragment development experience*.

I think there is an approach to keep-it-simple and achieve syntactic parity with other GraphQL frameworks.   

Adding a translation step that would inline each fragment into each operation before generating the client would support the fragment syntax, but keep the implementation bare-bones.

This means you would support fragments syntactically, have another core GraphQL feature under your belt, and everyone can use existing GraphQL tooling to be more productive.

...It would also give you time to do something fancier with fragments down the road with minimal breaking changes, if any.

**Comment by jensneuse** [comment]
Implemented: https://docs.wundergraph.com/docs/examples/fragments
