### ISSUE TITLE
[Issue]: Login Session Issue

### ISSUE THREAD

**Issue by raman-exiliensoft** [wundergraph/wundergraph#1153]
### Description

We are using Frontegg auth as an openID Connect in wundergraph but after successful login wundergraph takes 20 -25 seconds to set the user session unless we switch the window or click on the document.

It's happening frequently chrome incognito window.

Also previously we were using an Auth0 provider then this issue was not happening.

Can you please look into this issue?

Thanks
Raman Kumar 

### Reproduction

Just connect frontegg auth provider using openIdConnect in wundergraph 

![image](https://github.com/wundergraph/wundergraph/assets/114407340/d527817d-357c-43a3-b620-3bcd84790718)

https://www.loom.com/share/561ca68a129d400d9440c7dfbe6f98b7

**Comment by Pagebakers** [comment]
It seems like there might be a slow response somewhere in the oauth flow (communication between your server and frontegg), preventing the cookie from be set in time.

Can you also reproduce this on your local machine? You could add some logs in the authentication hooks to see where in the auth flow is the slow down.

**Comment by raman-exiliensoft** [comment]
@Pagebakers Thanks for checking.

I have reproduced it in the local machine as well and we are getting a response from Frontegg in Post Authentication in time.
