### ISSUE TITLE
[Issue]: Missing doc or broken link on Authorization page. 

### ISSUE THREAD

**Issue by jimmiebtlr** [wundergraph/wundergraph#1161]
### Description

On this page
https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/configure-authorization#how-rbac-works

The link "Configure Authorization Guide" takes you to an empty/non-existent page.
https://docs.wundergraph.com/docs/guides/configure-authorization

### Reproduction

Navigate to 
https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/configure-authorization#how-rbac-works

Click "Configure Authorization Guide"

**Comment by Pagebakers** [comment]
Thanks for reporting @jimmiebtlr we'll update this shortly.
