### ISSUE TITLE
Allow for persisted introspection outside of node_modules to assist CI/CD with private databases and networks

### ISSUE THREAD

**Issue by RayHughes** [wundergraph/wundergraph#1171]
## Problem

When building with a public CI/CD pipeline such as BitBucket Pipelines or Gitlab, the worker needs access to the database and virtual cloud. This creates a security vulnerability as the pipeline would need to be whitelisted at some level.

Wundergraph supports pre-generating (https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/configure-introspection#pregenerating-the-cache) but this stores the cache within `nodule_modules`, which best practice dictates to omit from version control.  

The current work arounds to this problem include using a private pipeline, committing the generated dir, or creating scripts to move the generated cache to and from the `node_modules` directory. All of these increase deployment complexity. Committing the generated directory results in secrets being exposed within git.

## Suggested solution

Add a`--persist-introspection` flag to `wunderctl generate` to allow for storing introspection cache outside of `node_modules` and the `.wundergraph/generated` directories. Developers could then commit the files to git which could then be introspected directly from `wunderctl generate --offline` 

## Alternatives

Allow for generating introspection from the `Schema.prisma` file offline.

## Additional context

From my understanding the Prisma introspection should work offline, but that does not seemed to be the case.

This can also assist private APIs where the open api files might not be readily available.

**Comment by Pagebakers** [comment]
Currently the cache dir is hardcoded to `node_modules/.cache/wundergraph/introspection`

Your suggested solution could work, or alternatively allow to configure a custom directory for the introspection cache. I will bring this up with the team tomorrow to see what solution is favoured.

Is this something you could contribute?

**Comment by RayHughes** [comment]
@Pagebakers Possibly, but likely not until mid fall.

I think specifying the directory would be a more sound approach as it will give the dev greater control.

**Comment by brampurnot** [comment]
Has this already been released? When I use the "--persist-introspection" flag, it says that it's unknown.

**Comment by bart-sofomo** [comment]
Yeah I was also under impression that when you provide `schema` file the introspection would be offline. It would be cool to have `--persist-introspection` flag.

**Comment by Pagebakers** [comment]
I've just tested this with the `introspect.prisma` with a local schema.prisma and that works offline. I don't think there any need for a persisted cache in this case.

**Comment by bart-sofomo** [comment]
@Pagebakers what do you mean that it works offline? Are you sure that you don't have db running in docker locally or something? Even if you use a schema it tries to reach db.
