### ISSUE TITLE
[Issue]: `_join` query with @internal directive yields error

### ISSUE THREAD

**Issue by stavan-vc** [wundergraph/wundergraph#1183]
### Description

I need to implement Cross API Joins for the response. Our goal is to utilize the _join query across multiple operations in order to retrieve data from various services.

However, an issue arises when I attempt to export the value of 'oid' to the variable 'soid' as the JOIN key. This action is causing an error within the _join query.

Here's the query I'm currently working with:

```
query ($soids: [Int]! = [], $site: Int! = 101, $soid: Int! @internal) {
  zone: test_getZoneList(soids: $soids, site: $site) {
    site
    oid @export(as: "soid")
    zone_type
    _join {
      objects(id: $soid) {
        name
      }
    }
  }
}
```

Here is the error from the operation.
```
"errors": [
    {
      "message": "Variable '$id' of required type 'Int!' was not provided.",
      "locations": [
        {
          "line": 1,
          "column": 7
        }
      ]
    },
    {
      "message": "Variable '$id' of required type 'Int!' was not provided.",
      "locations": [
        {
          "line": 1,
          "column": 7
        }
      ]
    }
  ],
```

**Comment by Pagebakers** [comment]
Could you share the type of the getZoneList query from the schema?

If possible do you have repo you can share so we can try to reproduce it?

**Comment by stavan-vc** [comment]
@Pagebakers , I would not be able to share the repository, but here is the type schema. 

query getZoneList(soids: [Int!]!, site: Int!): [Zone]

type Zone {
    """
    ID of the Object
    """
    oid: Int!

    """
    ID of the Site the object the Zone is assigned to
    """
    site: Int!

    """
    Type of the Zone
    """
    zone_type: ZoneType!
}

Also, is it possible that due to the response for the actual query and join are from different services, it is not detecting the variable?

**Comment by Pagebakers** [comment]
The purpose of _join is to join data from different services so that should work.

`objects` is actually an existing operation / query? or is it a field of the test_getZoneList, i'm asking because there doesn't seem to be a namespace.
