### ISSUE TITLE
Fetching schema from remote schema registry

### ISSUE THREAD

**Issue by screamz2k** [wundergraph/wundergraph#1187]
I am not sure, if there is already a solution for this, but it would be good, to have the possibility to fetch a schema from a remote schema registry like hive.
So for example in the code for the apollo federation ([link](https://docs.wundergraph.com/docs/apis/apollo-federation#add-a-apollo-federation-data-source)):
```js
import { configureWunderGraphApplication, introspect } from '@wundergraph/sdk';

const federatedApi = introspect.federation({
  apiNamespace: 'federated',
  upstreams: [
    {
      url: 'http://localhost:4001/graphql', // url of the service
      schema: 'https://url-to-your-schema.dev/' // url which only returns the schema of the service
    },
  ],
});

configureWunderGraphApplication({
  apis: [federatedApi],
});
```
This would allow to build the wundergraph docker image without depending on the activity of the services and only of the schema registry.

I also read about loadSchemaFromString(), should this method be used to fetch the schema from a remote registry and would it skip the step of querying it from the service itself?

**Comment by jensneuse** [comment]
You can await fetch a remote schema and pass it as schemaFromString value.

**Comment by screamz2k** [comment]
yeah that's what i wanted to try , but if i build the wundergraph, will the schema be stored or refetched on server start?

**Comment by fiam** [comment]
@screamz2k If you implement schemaFromString WunderGraph will refetch the schema when the server starts
