### ISSUE TITLE
Write an how to guide about how to debug hooks

### ISSUE THREAD

**Issue by AnsonCode** [wundergraph/wundergraph#119]
## Problem

I want to know how to debug hooks.

I have known that  hooks essentially is web server.But i have no idea about how to debug hooks.

Hope to provide documentation.

**Comment by jensneuse** [comment]
@StarpTech We should run `wunderctl up` with a param to disable building and (re-)running the hooks. Then, add a config to continuously build and run the hooks server, e.g. using ts-node with `--watch`. Once the flow works, it needs to be documented. I think it should already be available, more or less, just needs to be tried and documented.

**Comment by jensneuse** [comment]
@AnsonCode we're currently working on this. It's available soon. @StarpTech will update the docs once complete and let you know here in the issue.

**Comment by AnsonCode** [comment]
This is COOL! Looking forward to your work. @jensneuse
