### ISSUE TITLE
[Issue]: WG (openApiV2): Operation "RemoveCartEntry" throws "Unexpected response in removeCartEntry" error

### ISSUE THREAD

**Issue by Xymmer** [wundergraph/wundergraph#1196]
### Description

If the response is empty when status code is 200.

```
 responses:
        '200':
          description: OK
```
then "Unexpected response" error will be thrown.

If successful but no content, use status code 204 instead of 200.

### Reproduction

@wundergraph/sdk: 0.174.0

**Comment by Pagebakers** [comment]
@Xymmer a 200 status code should always have a response. The OAS introspection is strict in this regard and expects a valid JSON response in this case.

It would be best to update the schema to use 204 status code.
