### ISSUE TITLE
[Issue]: WG (openApiV2): enable orm make generation hanging

### ISSUE THREAD

**Issue by Xymmer** [wundergraph/wundergraph#1198]
### Description

Enable orm:

```
  experimental: {
    orm: true,
  },
```
The generation process is hanging. I can see the operations (graphql files) are generated, but only a few files are generated inside "generated" folder.

### Reproduction

Enable orm
@wundergraph/sdk: 0.174.0

**Comment by Pagebakers** [comment]
Generating the ORM with a large open api schema can take a while, in your case it keeps hanging for longer than a few minutes?

**Comment by Pagebakers** [comment]
The ORM is still experimental and not recommended to use with large schema's for now.
