### ISSUE TITLE
The lack of package："github.com/wundergraph/wundergraph/types/go/wgpb"

### ISSUE THREAD

**Issue by AnsonCode** [wundergraph/wundergraph#12]
### Bug description

When I run `cmd/wunderctl`, I get a error:
`../../pkg/loadvariable/loadvariable.go:8:2: no required module provides package github.com/wundergraph/wundergraph/types/go/wgpb; to add it:
        go get github.com/wundergraph/wundergraph/types/go/wgpb`

And find that The lack of package："github.com/wundergraph/wundergraph/types/go/wgpb"

### How to reproduce

1. Go to 'cmd/wunderctl'
2. Change 'nothing'
3. Run 'go run main.go'
4. See error:
`../../pkg/loadvariable/loadvariable.go:8:2: no required module provides package github.com/wundergraph/wundergraph/types/go/wgpb; to add it:
        go get github.com/wundergraph/wundergraph/types/go/wgpb`

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

2b16f968f7c18e1f3bb9dd205de21336220070bb

**Comment by jensneuse** [comment]
This should work after running make, can you confirm?

**Comment by AnsonCode** [comment]
when i run "make run",i get the error.

`anson@192 wgcode % make run
cd cmd/wunderctl && go run main.go
../../pkg/loadvariable/loadvariable.go:8:2: no required module provides package github.com/wundergraph/wundergraph/types/go/wgpb; to add it:
        go get github.com/wundergraph/wundergraph/types/go/wgpb
make: *** [run] Error 1`

**Comment by AnsonCode** [comment]
Do we have to use go version 1.8?

**Comment by AnsonCode** [comment]
Maybe i know the reason:i don't generate the code . I will have a try later.

**Comment by AnsonCode** [comment]
I have solve the issue by run `make`.
