### ISSUE TITLE
[Issue]: WG (openApiV2): Some PUT/POST methods throw "Request body is invalid or missing" error

### ISSUE THREAD

**Issue by Xymmer** [wundergraph/wundergraph#1200]
### Description

Some PUT/POST methods throw "Request body is invalid or missing" error, e.g. CreateUser.

We found that these requests sent to the backend have "Content-type: application/xml". (Content-type should be "**application/json**")

In our specification file, we have "requestBody" like this:

```
requestBody:
    content:
        application/xml:
            schema:
              $ref: '#/components/schemas/UserSignUp'
        application/json:
            schema:
              $ref: '#/components/schemas/UserSignUp'
```
There is a workaround to fix it:

It seems that the first content is used. If we remove "application/xml" or we put "application/json" before "application/xml", this issue will be gone.

### Reproduction

In description
@wundergraph/sdk: 0.174.0

**Comment by Pagebakers** [comment]
The fix has been merged, but not released yet.

**Comment by Pagebakers** [comment]
Released in upstream closing this issue now
