### ISSUE TITLE
[Issue]: Fetching GraphQL Schema on GraphQL endpoint fails

### ISSUE THREAD

**Issue by johnkm516** [wundergraph/wundergraph#1203]
### Description

I've looked everywhere in the docs but cannot find any solution for this. 

Per the docs, I've configured my Wundergraph like this : 

```
configureWunderGraphApplication({
	apis: [countries, weather, rest],
	server,
	operations,
	generate,
	cors: {
		...cors.allowAll,
		allowedOrigins: ['https://www.graphqlbin.com/', 'https://studio.apollographql.com/'],
		allowCredentials: true,
	},
	security: {
		enableGraphQLEndpoint: true,
	},
});
```

As said in the docs, by default, security is set to allow all hosts. CORS is set correctly. However, after deploying the graph, while localhost:9991/graphql shows the GraphiQL playground, if I try to use Apollo Sandbox instead it doesn't work. Nor does graphqlbin. 

I looked into the network portion in the browser console and I get alternating succeeding fetches and failed preflights : 

![image](https://github.com/wundergraph/wundergraph/assets/10858008/781884a1-a3fa-4b31-b31f-9b5521092df3)

The succeeding fetch shows the schema, but Apollo Sandbox ultimately shows that it cannot connect to server : 

![image](https://github.com/wundergraph/wundergraph/assets/10858008/2f957c77-df74-4e81-9be1-620565b98e9f)

What am I doing wrong here? The GraphiQL playground that comes out of the box with Wundergraph is helpful, but Apollo Sandbox allows you to basically point and click to build queries rather than write them out manually so I am trying to get this to work. If Wundergraph supports embedding Apollo Sandbox locally rather than GraphiQL that would be even better. 

### Reproduction

@wundergraph/sdk: 0.173.0

**Comment by Aenimus** [comment]
Please share whatever WunderGraph-related config you are sharing with Apollo.

**Comment by johnkm516** [comment]
> Please share whatever WunderGraph-related config you are sharing with Apollo.

I'm sorry but I don't understand what you mean by whatever WunderGraph related config that is shared with Apollo.
What I am trying to do is deploy Wundergraph locally using some public GraphQL (provided by the Wundergraph quick-start) and a public REST API, and then introspect the schema at [Apollo Sandbox here](https://studio.apollographql.com/sandbox/explorer?referrer=docs-nav). 

My config is almost exactly the same as the quick-start repo except for the code I provided above, to configure CORS and allowedOrigins and enable the GraphQL endpoint.

**Comment by Aenimus** [comment]
My apologies for being unclear. I just tested myself with my own graph, and it worked.

Can you confirm the sandbox url has been set to `http://localhost:XXXX/graphql` and the "light" is green (and not red)?

**Comment by johnkm516** [comment]
> My apologies for being unclear. I just tested myself with my own graph, and it worked.
> 
> Can you confirm the sandbox url has been set to `http://localhost:XXXX/graphql` and the "light" is green (and not red)?

The sandbox URL is set correctly, as I showed in my screenshots one of the fetch requests for the graph works. However the "light" is still red and I see no changes in the documentation. 

Did you test with the Wundergraph quick-start? Can you tell me what you did different from the quick-start that made it work?

**Comment by Aenimus** [comment]
Hi,

So the problem is that Apollo fails to introspect because the base definitions are not provided; e.g., scalars like `String` and `Float;` directives like `@deprecated`.  Providing these seems to fix the issue.

We're looking into how we can solve this.

**Comment by Aenimus** [comment]
Problem fully identified; fix in place. I'll let you know when the release is ready. Thanks again for the report!

**Comment by johnkm516** [comment]
> Problem fully identified; fix in place. I'll let you know when the release is ready. Thanks again for the report!

Thank you for your help!

**Comment by Aenimus** [comment]
Hi @johnkm516,

Please could you update your `package.json` to `"@wundergraph/sdk": "^0.174.5"`, run `npm i`, and then `wunderctl up`? I've just tested this, and everything should work as desired.

Please note that the `npx create-wundergraph-app` command itself hasn't yet been updated to use the newest version, but it will be soon.

Please let me know whether this fixes your problem, and I'll close the issue if it has.

Thanks once again for the report!

**Comment by johnkm516** [comment]
@Aenimus  

Works fine. Thank you!
