### ISSUE TITLE
[Issue]: Invalid Link to Architecture Documentation in README

### ISSUE THREAD

**Issue by KaranJagtiani** [wundergraph/wundergraph#1218]
### Description:
I encountered a broken link in the README when trying to navigate to the architecture documentation of WunderGraph.

In the section that provides a high-level overview of how WunderGraph functions, there's a statement:

"For a more thorough introduction, visit the [architecture](https://github.com/wundergraph/wundergraph/blob/main/docs/architecture) documentation."

The provided link leads to a 404 error on GitHub. Upon further inspection, I believe the issue is due to the missing .md extension in the URL.

### Reproduction:

1. Navigate to the main [README](https://github.com/wundergraph/wundergraph) of the WunderGraph project on GitHub.
2. Scroll down to the section "How does WunderGraph work" that provides a high-level overview of how WunderGraph works.
3. Within this section, find the statement: "For a more thorough introduction, visit the [architecture](https://github.com/wundergraph/wundergraph/blob/main/docs/architecture) documentation."
4. Click on the "architecture" hyperlink.
5. Observe that the link redirects to a 404 error page, indicating a broken link.

### Solution:
To resolve this, the link should be updated to:
https://github.com/wundergraph/wundergraph/blob/main/docs/architecture.md

This change ensures users can directly access the architecture documentation without encountering any errors.

**Comment by KaranJagtiani** [comment]
I've identified the issue with the broken link in the README and have a clear understanding of the necessary fix. I'd appreciate it if this issue could be assigned to me.

**Comment by Pagebakers** [comment]
We would be really happy to receive a PR for this, thank you.

**Comment by KaranJagtiani** [comment]
Thank you @Pagebakers! Glad I could contribute :)
