### ISSUE TITLE
[Issue]: Type information for generated operations is not applied to wundergraph client 

### ISSUE THREAD

**Issue by ercultimate** [wundergraph/wundergraph#1229]
### Description

When importing `client` from the generated WunderGraph nextjs module, the methods (query, mutate, etc...) do not have the operation input and response type information applied to them. The return type is `any`, the operation constraint is only `string`, and the input object is type `any`.

Actual:
```typescript
import { client } from '<generated_client_code>/nextjs';

// data is type `any`, 
const { data } = await client.query({ /* ... */ });
```

The expected behavior is that the type information is applied to the `client` methods similar to how the `useQuery`/`useMutation` react hooks have the input and output typed according to the operation.

Expected:
```typescript
import { useQuery } from '<generated_client_code>/nextjs';

// data is the return type of the respective query 
const { data } = useQuery({ /* ... */ })
```

### Reproduction

Versions:
**Runtime:** NodeJs 18.16.0
**Package Manager:** npm@9.5.1
**Installed dependencies:**
 -  `@wundergraph/nextjs@0.12.1`
 - `@wundergraph/react-query@0.8.49`
 - `@wundergraph/sdk@0.167.1`

_wundergraph.config_
```
configureWunderGraphApplication({
  ...baseConfig,
  generate: {
    ...baseConfig.generate,
    codeGenerators: [
      ...(baseConfig.generate?.codeGenerators ?? []),
      {
        templates: [new NextJsTemplate()],
        path: '../../libs/react-storefront-client',
      },
    ],
```

**Comment by Pagebakers** [comment]
Have you added the generated folder to `include` in your tsconfig.json?

**Comment by ercultimate** [comment]
Not explicitly, no.
_tsconfig.base.json_
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    /* ... */
    "paths": {
      "@cs/react-storefront-client/*": ["libs/react-storefront-client/*.ts"],
    }
  },
  "exclude": ["node_modules", "tmp"]
}
```

_tsconfig.json_
```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": { /* ... */ },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    "**/*.js",
    "**/*.jsx",
    "next-env.d.ts"
  ],
}
```

**Comment by ercultimate** [comment]
I don't feel like the tsconfig is an issue, given that the `useQuery` hook has the expected type constraints.  

I think it's related to the function from `@wundergraph/nextjs`
```typescript
declare const createWunderGraphNext: <Operations extends OperationsDefinition<_wundergraph_sdk_client.OperationDefinition, _wundergraph_sdk_client.OperationDefinition, _wundergraph_sdk_client.OperationDefinition, _wundergraph_sdk_client.OperationDefinition, string, _wundergraph_sdk_client.S3ProviderDefinition, string>>(options: WithWunderGraphOptions) => {
    useQuery: UseQueryHook<Operations, {
        ssr?: boolean | undefined;
    }>;
    useSubscription: UseSubscriptionHook<Operations, {
        ssr?: boolean | undefined;
    }>;
    useAuth: () => {
        login: (authProviderID: Operations["authProvider"], redirectURI?: string | undefined) => void;
        logout: (options?: _wundergraph_sdk_client.LogoutOptions | undefined) => Promise<boolean>;
    };
    useFileUpload: _wundergraph_swr.UseUploadHook<Operations>;
    useUser: _wundergraph_swr.UseUserHook<Operations>;
    useMutation: _wundergraph_swr.UseMutationHook<Operations, {}>;
    withWunderGraph: (AppOrPage: next.NextComponentType<any, any, any>, overrideOptions?: Partial<WithWunderGraphOptions> | undefined) => next.NextComponentType<next.NextPageContext, {}, {}>;
    client: _wundergraph_sdk_client.Client; // <-- ** HERE **
};
```

It seems like the type assigned to `client` does not receive the `Operation` type param that is given to `useMutation` and `useQuery`.

**Comment by Pagebakers** [comment]
Thanks for the info, your assumption is correct. The client isn't a generic type and so the types never inferred. I've opened an issue to address this.

**Comment by Pagebakers** [comment]
We'll be releasing an update soon. Please re-open this issue in case you keep having issue after the release.
