### ISSUE TITLE
[Feat] OpenAPIV2 Introspection does not allow to add custom headers

### ISSUE THREAD

**Issue by gvidaspr** [wundergraph/wundergraph#1231]
## Problem

I am using OpenAPIV2 Introspection to generate the Wundergraph client. The OpenAPI source is an URL, which is protected by Basic Authorization (USER:PASSWORD). GraphQL Introspection configuration allows to add custom headers to introspection requests, however, there is no such functionality for OpenAPI introspection.

## Suggested solution

Adding the possibility to alter the headers of OpenAPI introspection requests would solve this issue as the addition of Authorization header would become available.

## Additional context

This is the OpenAPI introspection configuration I was mentioning:
```js
const openApi = introspect.openApiV2({
  id: "rest",
  apiNamespace: "rest",
  source: {
    kind: "url",
    url: "http://localhost:3001/api-json",
  },
  introspection: {
    headers: (builder) =>
      builder.addStaticHeader(
        "Authorization",
        "Basic USER:PASS" // This part IS NOT supported by OpenAPI introspection configuration.
      ),
  },
});
```

GraphQL Introspection config:
```js
const graphql= introspect.graphql({
  apiNamespace: "graphql",
  url:  "http://localhost:8080/graphql",
  introspection: {
    headers: (builder) =>
      builder.addStaticHeader(
        "Authorization",
        "Basic USER:PASS" // This part IS supported by GraphQL introspection configuration.
      ),
  },
});
```

**Comment by gvidaspr** [comment]
@fiam just tested this feature - doesn't seem to work, or I am misusing it somehow. There is a NestJS application running on my local machine, providing Swagger UI and json docs. It is secured by [basic express auth](https://github.com/LionC/express-basic-auth). However, in the logs on NestJS, I am not able to see the request.

wundergraph.config.ts:
```js
const openapi = introspect.openApiV2({
  id: "openapi",
  apiNamespace: "openapi",
  source: {
    kind: "url",
    url: "http://localhost:3001/docs-json",
  },
  headers: (builder) => {
    builder.addStaticHeader("Authorization", "Basic TESTHEADER");
    return builder;
  },
});
```

NestJS received headers:
```json
{ "host": "localhost:3001", "connection": "close" }
```

What I would expect to have:
```json
{ "host": "localhost:3001", "connection": "close", "Authorization": "Basic TESTHEADER"  }
```

**Comment by fiam** [comment]
Hello @gvidaspr - We have an integration test for this. We include the header in this [test app](https://github.com/wundergraph/wundergraph/blob/main/packages/testsuite/apps/openapi/.wundergraph/wundergraph.config.ts#L58)  and we check its value in this [test server](https://github.com/wundergraph/wundergraph/blob/62f54b1a7fbfe23dc944b1c4ea0ee5332071208f/packages/testsuite/apps/openapi/openapi-spec-server.ts#L12). Could you double check your setup? Make sure you're running an SDK version recent enough.

**Comment by torchello** [comment]
Apparently, introspection headers need to be defined separately like [here](https://github.com/wundergraph/wundergraph/blob/main/packages/testsuite/apps/openapi/.wundergraph/wundergraph.config.ts#L73-L78).
