### ISSUE TITLE
Expose wundergraph to local network

### ISSUE THREAD

**Issue by lubiah** [wundergraph/wundergraph#1233]
## Problem

I'm currently using wundergraph inside my current project. How ever, I can't expose the port wundergraph uses to my local network. 

It would really be nice if this feature was implemented 

## Alternatives

Currently there are no alternatives

**Comment by gvidaspr** [comment]
What do you mean you can't expose the port wundergraph uses to your local network? The Wundergraph instance, (`wunderctl up`) should be running on your local machine and accessible by whichever port you have configured. Could you please provide more details of your configuration and the setup you are trying to achieve?

**Comment by lubiah** [comment]
Hi, thanks for getting back to me.

When I use Vite, it has an option "host" that allows other devices to connect to your Vite application on localhost but I'm unable to achieve that with Wundergraph. Each time I try accessing the port

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by lubiah** [comment]
@Pagebakers , Yes, it can be accessed on 127.0.0.1:9991. 
But what I want to achieve is access the same port on my mobile device that's why I used `vite --host` as an example.
Vite doesn't expose that port by default unless you use the host option. After using it, you will be able to access the same port on any device which has connected to your computer.

For example, it allows you to view that port on your mobile device through your computer's I.P address or any device which has connected to the computer's network can also view the contents on the Vite server.

Right now, I'm using vite with Wundergraph and it's working fine but since the 'My computer IP:9991' isn't exposed. I'm not able to use Wundergraph on my mobile device on any device which has connected to my computer's network.
Here's the [docs for Vite host](https://v3.vitejs.dev/config/server-options.html), maybe it will explain what I want to acheive

**Comment by fiam** [comment]
Hello @lubiah - Please use `WG_NODE_HOST=0.0.0.0 vite ...`, that will make wunderctl listen in all interfaces

**Comment by lubiah** [comment]
Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Pagebakers** [comment]
@lubiah You last message is empty, did this resolve your issue?

**Comment by lubiah** [comment]
@Pagebakers , yes I was able to resolve the issue
