### ISSUE TITLE
[Issue]: // redirect in auth0

### ISSUE THREAD

**Issue by rwest202** [wundergraph/wundergraph#1260]
### Description

https://github.com/wundergraph/wundergraph/commit/4fe0d66a32e286d782e39945ed3cf3f74b048cad#r126538243

@Pagebakers

I'm now getting this on my auth0 redirect:

invalid_request: The redirect_uri parameter is not valid: "//localhost:9991/auth/cookie/callback/login" If url looks fine, check that you are not including non printable chars

I can fix this by switching the scheme to "http://", however I don't know if that breaks the original use case you designed for. Can you test further, this blocks my local development flow on the latest wunderctl version.

### Reproduction

Add an auth0 provider, start your local development server, run `login('auth0')` on the frontend from the typescript client.

**Comment by rwest202** [comment]
@Pagebakers - my bad if you got notified 3 times! Wanted to make sure you saw since this was committed into the most recent wunderctl release.

**Comment by fiam** [comment]
Thanks for heads up @rwest202 - This should be now fixed with SDK 0.178
