### ISSUE TITLE
[Issue]: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [wundergraph/wundergraph#1264]
### Description

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

### Screenshot
<img width="960" alt="Screenshot 2023-09-07 171714" src="https://github.com/wundergraph/wundergraph/assets/91591901/1a6ca41a-74bb-4f3c-91c4-1672b56e38bf">

### Reproduction

Go to the footer section and see Twitter old logo

@fiam 
I am willing to work on this issue please assign it to me?

**Comment by Pagebakers** [comment]
The website is not public unfortunately. I'll open an internal issue to update it, thanks for reporting!
