### ISSUE TITLE
[Issue]: ERROR: "wundergraph" exited with 1.

### ISSUE THREAD

**Issue by supercoolx** [wundergraph/wundergraph#1282]
### Description

I want to start project with wundergraph and next.js.
But it doesn't work.

```
npx create-wundergraph-app my-project -E nextjs
cd my-project
npm i
npm start
```
I run these scripts, but it shows error
```
> wundergraph-nextjs@0.1.0 start
> run-p dev wundergraph open


> wundergraph-nextjs@0.1.0 dev
> next dev


> wundergraph-nextjs@0.1.0 open
> wait-on -d 500 http://localhost:9991 && open-cli http://localhost:3000


> wundergraph-nextjs@0.1.0 wundergraph
> wunderctl up

ERROR: "wundergraph" exited with 1.
```
How to use it?
Node version is v18.16.1 and OS is Windows 10.

### Reproduction

node version: v18.16.1
OS: Windows 10

**Comment by ShaneMaglangit** [comment]
A quick fix for this is to run each script individually.

```bash
npm run dev
wunderctl up
```

You don't need the third one, just go to http://localhost:3000

**Comment by fiam** [comment]
Hello @supercoolx - Thanks for the heads up. This was fixed a couple of releases ago. Please, update `@wundergraph/sdk` and `@wundergraph/nextjs` to the latest version and then it should work.
