### ISSUE TITLE
[Issue]: OpenApiV2 introspection shows compilation issue for `wunderctl up` when components schema contains the name `Time`

### ISSUE THREAD

**Issue by bgambocjaviniar** [wundergraph/wundergraph#1290]
### Description

When introspecting a yaml file of OpenAPI 3.0 using `openApiV2` of introspect from @wundergraph/sdk, it throws an error using `wunderctl up` when the yaml (OAS 3) contains the components schema named "Time".
- it does not complain when using `wunderctl generate`

For example:

```yaml
components:
     schemas:
            SomeSchema:
               type: object
               properties:
                   opening:
                       $ref: '#/components/schemas/Time'
                   closing:
                       $ref: '#/components/schemas/Time'               
                       ...
                ....
            Time:
               type: object
               properties:
                   hour:
                       type: string
                   minute:
                       type: string
```

# **Important note:**
- This thrown error does not occur for `openApi` (v1) of introspect from @wundergraph/sdk
- No errors related to this found using [swagger-editor ](https://github.com/swagger-api/swagger-editor)
- schemas were validated and generated using the [openapi generator from openapi tools](https://www.npmjs.com/package/@openapitools/openapi-generator-cli)
- `changing` time name of `Time` component schema to something other than `Time`, such as `TimeAbc` will make wundergraph generation work.

### Reproduction

- running `wunderctl up` with the details below

Version:
`@wundergraph/sdk@0.167.1` 

wundergraph.config.ts:
```ts
const someNameSpace = introspect.openApiV2({
  apiNamespace: 'someNamespace',
  source: {
    kind: 'file',
    filePath: '../shared-bff/specs/aopenapiv3specification.yaml',
  },
  baseURL: 'https://someUrl.com/',
  headers: (builder) =>
    builder.addClientRequestHeader('Authorization', 'Authorization'),
});
```

aopenapiv3specification.yaml:

For example:

```yaml
components:
     schemas:
            SomeSchema:
               type: object
               properties:
                   opening:
                       $ref: '#/components/schemas/Time'
                   closing:
                       $ref: '#/components/schemas/Time'               
                       ...
                ....
            Time:
               type: object
               properties:
                   hour:
                       type: string
                   minute:
                       type: string
```

**Comment by Pagebakers** [comment]
To be clear, when you run `wunderctl generate` it generates your operations correctly?

Can you share the error that's thrown?

**Comment by bgambocjaviniar** [comment]
> To be clear, when you run wunderctl generate it generates your operations correctly?

yes

> Can you share the error that's thrown?

Just to re-iterate, once we change the component's schema name from `Time` to anything but Time like `TimeAbc`, it will work

```json
{"level":"error","time":1694409074897,"caller":"node/node.go:601","msg":"BuildAndMountApiHandler","hostname":"C02FQ2ZEMD6R","pid":53763,"component":"@wundergraph/node","error":"operation planning failed: internal: validation failed: external: non scalar field: closing on type: SomeSchema must have selections,
...
```
