### ISSUE TITLE
[Issue]: Not being able to send an array of strings for operations that requires them as query params

### ISSUE THREAD

**Issue by bgambocjaviniar** [wundergraph/wundergraph#1291]
### Description

Sending an array of strings for one of the input's property for an operation is not being sent to the API server accordingly.
Moreover, looking at the `debugTransport` logs after making the request, the query param for the array of strings is non-existent. In other words, using the example below, someListsParam query param was not found the wg server is making the request to our api server.
I expected the client to properly convert and encode these query params accordingly before sending to the api server

Note: 
- storefront -> wg server (I can see it encoded the array of strings literally. Like encoding `[`, `]`, `:`, `"` for the array of strings
- wg server -> api server (query param does not exist) 

For example:

- an operation that supports a query params, which accepts an array of string

```yaml
paths:
     /some/path/userId/something:
       post:
            - name: someListsParam
               in: query
               required: false
               schema:
                    type: array
                    items:
                         type: string
            ...
            responses:
               "200":
                   description:  OK
           ...
```

# **Important note:**
- schemas were validated and generated using the [openapi generator from openapi tools](https://www.npmjs.com/package/@openapitools/openapi-generator-cli). I was also able to use the typescript-fetch from there to send an array of strings to the same consumed OAS yaml that we provide to the instrospection.

### Reproduction

- running `wunderctl generate` with the details below
- using openapi (v1)

Version:
`@wundergraph/sdk@0.167.1` 

wundergraph.config.ts:
```ts
const someNamespace = introspect.openApi({
  apiNamespace: 'someNamespace',
  source: {
    kind: 'file',
    filePath: '../shared-bff/specs/aopenapiv3specification.yaml',
  },
  baseURL: 'https://someUrl.com/',
  statusCodeUnions: true,
  headers: (builder) =>
    builder.addClientRequestHeader('Authorization', 'Authorization'),
});
```

aopenapiv3specification.yaml:

```yaml
paths:
     /some/path/userId/something:
       post:
            - name: someListsParam
               in: query
               required: false
               schema:
                    type: array
                    items:
                         type: string
            ...
            responses:
               "200":
                   description:  OK
           ...
```

**Comment by fiam** [comment]
I've tested this with `openApiV2()` and it seems to be working
