### ISSUE TITLE
[Issue]: WG not sending query params when `statusCodeUnions` is `true`

### ISSUE THREAD

**Issue by znikola** [wundergraph/wundergraph#1293]
### Description

We noticed an issue where WunderGraph (WG) does not send query parameters to the API server when `statusCodeUnions` config is enabled in `openApi()`. 

For a more detailed explanation with steps to reproduce please take a look at this repo's README: https://github.com/znikola/wg-query-params-problem

### Reproduction

1. `git clone git@github.com:znikola/wg-query-params-problem.git`
2. `npm ci` - install dependencies
3. `npm run build` - cleans and generates wundergraph files
4. `npm run start` - starts the WG server in debug mode
5. `npx ts-node good.ts` - runs a script which demonstrates WG was able to successfully send the query parameters and resolve the API server's response. In the WG's logs, we can see `GET /Wizards?FirstName=Tom&LastName=Riddle HTTP/1.1` confirming the query params have been sent.
6. `npx ts-node bad.ts` - runs a script and demonstrates a case where WG was not able to send query params. This can be confirmed in the WG's logs where we can see `GET /Wizards HTTP/1.1` w/o query params. Because there are no query params, API server responded with all wizards, which can be seen in the WG's logs.

**Comment by Pagebakers** [comment]
Thanks a lot for the reproduction.

We will no longer support openapi v1 in the future and recommend switch to `introspect.openApiV2` which will most likely also resolve this issue.
