### ISSUE TITLE
'SWRConfig' is not exported from '@wundergraph/swr'

### ISSUE THREAD

**Issue by brampurnot** [wundergraph/wundergraph#1296]
### Description

I followed the tutorial below to get a basic Wundergraph app working with NextJS:
https://docs.wundergraph.com/docs/getting-started/nextjs-quickstart

It works fine and I'm able to run the server locally too. However when trying to build the application, I'm getting the below error:
```
 ✓ Linting and checking validity of types    
Failed to compile.

./node_modules/@wundergraph/nextjs/dist/index.mjs
Attempted import error: 'SWRConfig' is not exported from '@wundergraph/swr' (imported as 'SWRConfig').

Import trace for requested module:
./node_modules/@wundergraph/nextjs/dist/index.mjs
./components/generated/nextjs.ts
```

I searched on Git and Google but wasn't able to find anything that could help me. I'm on the latest version of the Wundergraph SDK and Wundergraph Next package. 

Bram

### Reproduction

Follow this tutorial:
https://docs.wundergraph.com/docs/getting-started/nextjs-quickstart

**Comment by fiam** [comment]
Hello @brampurnot, thanks for your report.

We're not able to reproduce this, the following sequence of commands produces no error on our end:

```
npx create-wundergraph-app my-project --example nextjs  
cd my-project
npm run build:wundergraph
npm run check
npm run build:next 
```

Additionally, we can manually see that @wundergraph/swr does export SWRConfig:

```
$ grep SWRConfig node_modules/@wundergraph/swr/dist/index.d.ts
                                                          
import { SWRConfiguration, SWRResponse, Key } from 'swr';
export { SWRConfig, useSWRConfig } from 'swr';
type UseQueryOptions<Data, Error, Input extends object | undefined, OperationName extends string, LiveQuery> = Omit<SWRConfiguration<Data, Error>, 'fetcher'> & WithInput<Input, {
interface UseUserOptions<User> extends FetchUserRequestOptions, SWRConfiguration<User> {
```

Could you please share the `package.json` that's being generated on your end? That might give us more information.

**Comment by brampurnot** [comment]
Thanks! I actually updated the wundergraph packages and now it seems to work! Not sure what happened.
