### ISSUE TITLE
[Issue]: mock server not working as expected

### ISSUE THREAD

**Issue by znikola** [wundergraph/wundergraph#1299]
### Description

It appears that testing TS operations w/ WG is not working as expected.

We have:
1. a TS operation
2. which composes graphql operation(s)

We want to:
1. test the TS operation
2. by mocking the graphql operation(s)
3. and asserting the composed result in the test

[Mocking section](https://docs.wundergraph.com/docs/guides/mocking) in Wundergraph docs was used as the source for writing the test.

### Reproduction

Please see this repo: https://github.com/znikola/wg-ts-testing-problem

**Comment by StarpTech** [comment]
Hi @znikola, thanks for reporting and the example. We'll look into it.

**Comment by fiam** [comment]
We've fixed the example in https://github.com/znikola/wg-ts-testing-problem/pull/1
