### ISSUE TITLE
[Issue]: Live queries are not working when running server in debug mode (SvelteKit)

### ISSUE THREAD

**Issue by torchello** [wundergraph/wundergraph#1317]
### Description

I'm using live queries with SvelteKit. If I run server with `--debug` option eventsource request is never successful (stuck in pending state and updates are not received):

<img width="1049" alt="image" src="https://github.com/wundergraph/wundergraph/assets/897885/1b2cbe3b-0ca7-43f7-89d6-c3c128ca9195">

### Reproduction

Easy to reproduce on the example project by changing [this line](https://github.com/wundergraph/wundergraph/blob/main/examples/sveltekit/package.json#L12) to:
```
"wundergraph": "wunderctl up --debug",
```

**Comment by Pagebakers** [comment]
We found the issue, it's a problem in the live query handler, not related to svelte. We'll publish a fix soon.

**Comment by torchello** [comment]
Thanks! 🔥
