### ISSUE TITLE
[Issue]: Nextjs token based auth is not secure

### ISSUE THREAD

**Issue by bart-sofomo** [wundergraph/wundergraph#1320]
### Description

Hi,
I'm trying to implement https://docs.wundergraph.com/docs/auth/token-based-auth/auth-js but it will always work even if you setup empty `Bearer` token

### Reproduction

When setting up `userInfoEndpoint` like:
```  
authentication: {
    tokenBased: {
      providers: [
        {
          userInfoEndpoint: `${process.env.MY_APP}/api/auth/session`,
        },
      ],
    },
  },
```
there is an issue that `/api/auth/session` from nextauth is basically resolving in `{}` empty object. 
The reason for that is wundergraph is attaching `Authorization` header while nextauth is expecting `next-auth.session-token` cookie in order to display any info.
Then probably I could check if there is any user info inside `mutatingPostAuthentication` but right now it would allow everyone with url to wundergraph to use it - you just have to provide empty Bearer token.

I think the example is either outdated or it was never working as expected.

**Comment by Pagebakers** [comment]
Have you enabled authentication on all your operations?

https://docs.wundergraph.com/docs/wundergraph-operations-ts-reference/configure-authentication

**Comment by bart-sofomo** [comment]
@Pagebakers obviously I did:
```  
operations: {
    defaultConfig: {
      authentication: {
        required: true,
      },
    },
```

I think I know what is missing in the tutorial. Basically the NEXTJS_URL/api/wg/* is secured but when I directly call WUNDERGRAPH_URL/operations without the rewrite in NEXTJS -> that's when it's get tricky. When you do that you an put any kind of token like `Beared xyz` and wundergraph would still response because it is getting 200 and `{}` from /api/auth/session.

**Comment by Pagebakers** [comment]
Thanks for the extra info. In that case the /api/auth/session response should throw an error in case the token is invalid. I'llr un some tests to verify this is broken.

**Comment by Pagebakers** [comment]
I've tested it, and indeed requests are always accepted because the session endpoint doesn't throw an error when the session isn't valid.

You can create a new `userInfo.ts` handler in `api/auth/userInfo.ts` with the following code:

```ts
import { getToken } from 'next-auth/jwt';

export default async (req, res) => {
	// If you don't have NEXTAUTH_SECRET set, you will have to pass your secret as `secret` to `getToken`
	const token = await getToken({ req });
	if (token) {
		res.status(200);
		res.json({ name: token.name, email: token.email, picture: token.picture });
	} else {
		// Not Signed in
		res.status(401);
	}
	res.end();
};
```
And then update the `userInfoEndpoint` in `wundergraph.config.ts` to point to the userInfo handler instead.

This way you can also map nextauth user details to the wundergraph claims.

**Comment by Pagebakers** [comment]
Docs have been updated, closing this for now.
