### ISSUE TITLE
Support for @tanstack/react-query v5

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#1321]
## Problem

It doesn't look like the WG react-query package supports some of the new hooks from react-query v5? Looks like v5 just went stable (https://www.npmjs.com/package/@tanstack/react-query?activeTab=versions) and is now the default when doing `yarn add @tanstack/react-query`. 

I think *most* of the WG react-query package would work since it is mostly a wrapper, but there are at least 3 new hooks that aren't present: `useSuspenseQuery`, `useSuspenseInfiniteQuery`, and `useSuspenseQueries`

## Suggested solution

Update WG react-query to support v5

## Additional context

There is a document showing the changes from v4 -> v5:
https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5

**Comment by Pagebakers** [comment]
I just read up on the changes yesterday, adding the new hooks is most of the work as far as I can see. 

We'd need to update React, Svelte and Solid query. 

Something you could help with?
