### ISSUE TITLE
[Issue]: TestServer start timeout artificially limited to maximum of 60s

### ISSUE THREAD

**Issue by ercultimate** [wundergraph/wundergraph#1343]
### Description

There is an issue with the new timeout feature for test server startup.  There is a hard limit of 60s still in place.
We needed more time for our test server to reliably start up, so we set 100s for a timeout.  When running the tests, however, the server still times out after only 60s.

This appears to be caused by the configuration passed to `retry(...)` not setting the timeout limit to 'INFINITELY' or the provided timeout value.
https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/testing/test-server.ts#L218

See 60s timeout default for `retry(...)` listed here: https://www.npmjs.com/package/ts-retry-promise#configuration

Versions
- node `18.16.0`
- npm `9.5.1`
- @wundergraph/sdk `0.181.1`

### Reproduction

Reproducing the issue would require over 200 standard operations and/or a resource-limited environment to run the tests in (such as an underpowered Jenkins server).

Here is an example of the configuration
ex: Test setup
```ts
const wg = createTestAndMockServer();

beforeAll(() => wg.start({
    timeout: 100000, // Process will timeout at 60000ms
}));
afterAll(() => wg.stop());
```

**Comment by Pagebakers** [comment]
Please update to `0.181.2` , the limit has been removed.
