### ISSUE TITLE
Object literal may only specify known properties, and 'type' does not exist in type 'JSONSchema7'

### ISSUE THREAD

**Issue by brampurnot** [wundergraph/wundergraph#1345]
### Description

I'm using Wundergraph with the nextjs client. When looking at the jsonschema.ts that gets generated, I see the following errors:
Object literal may only specify known properties, and 'type' does not exist in type 'JSONSchema7'

This now seems to be causing issues when doing a next build. Has anyone faced this before? I'm on all the latest versions. 

### Reproduction

run a next build command.

**Comment by fiam** [comment]
Hello @brampurnot - Could you please let us know if this is happening with one of the examples / templates or in your own project? We would need some context to reproduce this. Thanks!

**Comment by brampurnot** [comment]
Sorry for the late reply. This is happening in my own project. Never had any issues but all of a sudden this happened. I'm able to build it by setting the "ignoreBuildErrors" to true in the next JS config file but that's not ideal.

**Comment by brampurnot** [comment]
Here you go!
[Archive.zip](https://github.com/wundergraph/wundergraph/files/13697457/Archive.zip)
