### ISSUE TITLE
[Issue]: Nextjs App Router Migration Problem

### ISSUE THREAD

**Issue by yessGlory17** [wundergraph/wundergraph#1350]
### Description

Hello, I created a project with wundergraph nextjs project quick launcher. And I'm trying to do router migration (https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration) in nextjs documentation, but I'm getting the following error. I think this error is caused by Wundergraph. How can I solve this problem? Or when will Wundergraph start supporting nextjs' new router?

I added the image of the resulting error.

I also created a github repository below which gives the same error.

I need urgent help regarding this issue.
![image](https://github.com/wundergraph/wundergraph/assets/52113663/2b8da837-f046-4e64-b9e5-6d73cc7ad57d)

https://github.com/yessGlory17/wundergraph-next-router-migration

node:  v18
next: 14.0.1

### Reproduction

The error occurs when Nextjs app tries to migrate the router. Also, in your examples there is only an example of the old router.

**Comment by kyuumeitai** [comment]
I'm on the same boat as you. I think there's no way to use with app router, at least from now. For the sake of seeking workarounds, your error happens to me when I try to call it in a page, like this:

```
import { MainTrivia } from '@/components/main-trivia'
import { useQuery, withWunderGraph } from '@/generated/nextjs'
import { NextPage } from 'next'

const Home: NextPage = () => {
  const questions = useQuery({
    operationName: 'survey/Questions',
    input: {
      id: '65610b6e03500e299a29d52d',
    },
  })

  return (
    <div className="container relative">
      <section>
        <MainTrivia questions={questions} />
      </section>
    </div>
  )
}

export default withWunderGraph(Home)
```

node: v18
next: 14.0.3

The thing that works is to fetch directly to the wundergraph server (for example:        `http://127.0.0.1:9991/app/main/operations/AlbumById?albumId=${props.params.id}` ) as in this blog post:

https://wundergraph.com/blog/data_fetching_with_next13

the thing is that I don't want to leave the `wunderctl up` in prod.

Maybe someone has some solution or workaround for nextjs app layout based?

**Comment by kyuumeitai** [comment]
Digging further: I've tried to run client directly, as in [this example project](https://github.com/wundergraph/wundergraph/tree/main/examples/nextjs-app-dir). However, if you look closer to the `package.json`, the `build` process looks like this:

```    "build": "wunderctl generate && next build", ```

But, the `start` process:

```    "start": "npm run dev"```

and not the standard `next start`, making the `wunderctl up` mandatory :(

Is there a way to get only the generated types but tell wundergraph like 'ok, if the env is PROD, call the original `api.url` defined in the apis section of `configureWunderGraphApplication`'?

**Comment by Pagebakers** [comment]
Any page or component where you use React state needs to be client component, same goes for useQuery, useMutation.

https://github.com/yessGlory17/wundergraph-next-router-migration/blob/master/app/page.tsx#L1

The page should have `'use client'` directive.

You can use the WunderGraph typescript client directly in server components.

```const { data } = await client.query({
  operationName: 'Dragons'
})

**Comment by Pagebakers** [comment]
By the way, here's also an example with the app dir.
https://github.com/wundergraph/wundergraph/tree/main/examples/nextjs-app-dir
