### ISSUE TITLE
introspect.graphql does not work for Contetnful GQL Schema

### ISSUE THREAD

**Issue by uroslates** [wundergraph/wundergraph#1351]
### Description

When trying to introspect Contetnful's graphql schema by using

```
const contentful = introspect.graphql({
  apiNamespace: 'contentful',
  url: `https://graphql.contentful.com/content/v1/spaces/${CONTENTFUL_SPACE}/environments/${CONTENTFUL_ENV}`,
  headers: (builder) =>  builder.addStaticHeader('Authorization', CONTENTFUL_TOKEN),
});
```

wundegraph's generated graphql operations are invalid causing build to fail.

### Reproduction

node version v18.18.2
npm version 9.8.1
@wundergraph/sdk: "^0.181.2"

**Comment by Pagebakers** [comment]
I would assume that will solve most of the issues as well. I'm going to do some investigation to get an idea how much work it will be to implement this.

**Comment by Pagebakers** [comment]
We introduced a new `setOptions(namespace, options)` method in the generator to resolve this.
