### ISSUE TITLE
Event stream responses are missing the X-Accel-Buffering header

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#136]
### Bug description

I've been testing the Live Queries feature and it works well locally. But when I put Wundergraph behind the nginx in my cluster, the nginx seems to buffer the response from the server and the client's request is stuck in a loading state for a long time.

From my research, (e.g., see [here](https://serverfault.com/a/801629)), there are a bunch of settings I need to change in my nginx config - I can do these myself. But in addition, ideally, the Wundergraph server should also add a header `X-Accel-Buffering: no;` in its response.

I'm not too familiar with your code base, but I suppose you probably just need to add the header somewhere [here](https://github.com/wundergraph/wundergraph/blob/111d0c4b05b41c75fc76b3ad23be691582506d5a/pkg/apihandler/apihandler.go#L778), [here](https://github.com/wundergraph/wundergraph/blob/111d0c4b05b41c75fc76b3ad23be691582506d5a/pkg/apihandler/apihandler.go#L1085), or [here](https://github.com/wundergraph/wundergraph/blob/111d0c4b05b41c75fc76b3ad23be691582506d5a/pkg/apihandler/apihandler.go#L1703).

### How to reproduce

I didn't have time to come up with a minimum reproducible example, as my entire server setup is fairly complex. But I think from the discussion in [Serverfault thread](https://serverfault.com/a/801629), it should make sense to add the X-Accel-Buffering header in the server response for streaming events.

### Environment & setup

- OS: Ubuntu

### WunderCtl Version

```
Version: 0.97.0
Commit: 9473809239b83d337906fa6c2346863fa1748b71
Date: 2022-08-09T11:30:39Z
BuiltBy: ci
```

**Comment by jensneuse** [comment]
Seems legit. We'll have a look and will probably need your help with verifying the fix. @StarpTech thoughts?

**Comment by StarpTech** [comment]
Hi, looks good to me. I'll try to reproduce it and prepare the first draft.

**Comment by YuriBuerov** [comment]
Fixed [By](https://github.com/wundergraph/wundergraph/pull/157)
