### ISSUE TITLE
Support ability to include Tags in the OpenAPI spec generation

### ISSUE THREAD

**Issue by denniswieczorek** [wundergraph/wundergraph#1378]
## Problem

As far as I can tell, it is not currently possible to create operations in a way so that they can be grouped in the generated OpenAPI spec.

### Use Tags

OpenAPI's [Operation Object](https://spec.openapis.org/oas/latest.html#operation-object) supports the concept of `tags` to organize operations.

From the docs:
```
A list of tags for API documentation control. 
Tags can be used for logical grouping of operations by resources or any other qualifier.
```

### Implementation

An optional `tags` parameter on `createOperation.query`, `createOperation.mutation`, `createOperation.subscribe` that is  consumed in the OpenApiBuilder to add `tags` to the generated spec.

e.g.

```
// foo/bar.ts
export default createOperation.query({
  input,
  tags: ['Foo'],
  handler: () => {...},
})
```

Would produce something like

```
...
"paths": {
    "/foo/bar": {
      "get": {
        "tags": ["Foo"],
        "operationId": "...",
        "parameters": [...],
        "responses": {...},
      },
    },
...
```

## Alternatives

None that I can think of.

**Comment by acdn-tsmith** [comment]
PR: https://github.com/wundergraph/wundergraph/pull/1382
