### ISSUE TITLE
Watcher crashes if there are no fragments or webhooks

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#138]
### Bug description

A slightly annoying bug on newer wunderctl versions (I think starting from 0.98.0). If I don't have a `.wundergraph/webhooks` or `.wundergraph/fragments` directory, then the watcher crashes with error, e.g.:

```
error   Could not watch files   {"watcherName": "config-bundler", "error": "lstat /app/services/api/.wundergraph/webhooks: no such file or directory"}
```

and afterward, any change to `.wundergraph` will no longer trigger reload.

If I add a dummy fragment and webhook, then hot reload works again.

### How to reproduce

1. Open https://github.com/wundergraph/wundergraph-demo in Gitpod
2. Update wunderctl to `^0.98.0`
3. Try changing a file in `api/.wundergraph/operations`
4. Reload is no longer triggered.

### Expected behavior

Hot reload should work in projects without any fragment or webhook.

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```
Version: 0.99.1
Commit: cdeeda2095e9bf0f356b55a064e2a977db51b8bd
Date: 2022-08-18T19:44:12Z
BuiltBy: ci
```

**Comment by jensneuse** [comment]
Can you try 0.98.1?

**Comment by alasdairtran** [comment]
It's the same error. I guess you might want to add a directory to the watch list only if it exists.

**Comment by StarpTech** [comment]
Hi @alasdairtran thanks for reporting. Will look into it and provide a fix.
