### ISSUE TITLE
[Issue]: wunderctl generate fails to generate schema due to Allocation failed - JavaScript heap out of memory and very slow (>20 minutes)

### ISSUE THREAD

**Issue by TheMaximeBatandeoExperience** [wundergraph/wundergraph#1395]
### Description

When i try to run the script wunderctl generate I identified two situations where I face the issue out of memory. 

- First when i try to auto generate operations for a neo4J database (via neo4JGraphQL) that I use for experimentation 
- Second when after creating 18 GraphQL operations, the building operations takes forever (>20 minutes) before fails
The logs 
> web@1.0.0 dev
> wunderctl generate && concurrently "npx wunderctl up --debug" "npx relay-compiler --watch" "next dev"

{"level":"info","time":1719046308773,"pid":256,"hostname":"DESKTOP-1MH1IN4","component":"@wundergraph/sdk","sdk":"0.184.2","wunderctl":"0.180.0","msg":"Building ..."}
{"level":"info","time":1719046310706,"pid":256,"hostname":"DESKTOP-1MH1IN4","component":"@wundergraph/sdk","msg":"found 17 GraphQL operations"}
{"level":"warn","time":1719046577704,"pid":256,"hostname":"DESKTOP-1MH1IN4","component":"@wundergraph/sdk","msg":"To enable the ORM set `experimental.orm` to `true` in your `wundergraph.config.ts`."}

<--- Last few GCs --->

[256:0000025539473700]   826143 ms: Mark-Compact (reduce) 3847.8 (3907.9) -> 3847.7 (3907.6) MB, 3189.58 / 0.00 ms  (average mu = 0.921, current mu = 0.000) last resort; GC in old space requested
[256:0000025539473700]   829260 ms: Mark-Compact (reduce) 3847.7 (3907.6) -> 3847.7 (3907.6) MB, 3117.00 / 0.00 ms  (average mu = 0.849, current mu = 0.000) last resort; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF60B3DC4CB node::SetCppgcReference+17979
 2: 00007FF60B346324 DSA_meth_get_flags+89316
 3: 00007FF60BDC4461 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF60BDADBB8 v8::Function::Experimental_IsNopFunction+1336
 5: 00007FF60BC231E3 v8::Platform::SystemClockTimeMillis+740099
 6: 00007FF60BC2AEAE v8::Platform::SystemClockTimeMillis+772046
 7: 00007FF60BC3F6EA v8::Platform::SystemClockTimeMillis+856074
 8: 00007FF60BC3F9D3 v8::Platform::SystemClockTimeMillis+856819
 9: 00007FF60B9D3143 v8::base::Thread::StartSynchronously+484227
10: 00007FF60B9E9ECC v8::base::Thread::StartSynchronously+577804
11: 00007FF60B9EECEB v8::base::Thread::StartSynchronously+597803
12: 00007FF60B8FCC07 v8::CodeEvent::GetFunctionName+162615
13: 00007FF60BE75D8E v8::PropertyDescriptor::writable+677998
14: 00007FF60BE71477 v8::PropertyDescriptor::writable+659287
15: 00007FF60BE6FF12 v8::PropertyDescriptor::writable+653810
16: 00007FF5E7F52351
Error: configuration could not be generated. Process exit with code 134
configuration could not be generated. Process exit with code 134

### Reproduction

Connect a Neo4J database with 40 labels nodes, 100 relationships types, 200 properties running on a GraphQL server (yoga)
20 GraphQL operations
Run wunderctl generate

**Comment by RayHughes** [comment]
Configure `max_old_space_size` in your package.json

Here is an example of ours

```json
  "scripts": {
    "start": "wunderctl start --log-level error",
    "dev": "NODE_OPTIONS=--max_old_space_size=8192 wunderctl up --log-level error",
    "generate": "NODE_OPTIONS=--max_old_space_size=8192 wunderctl generate",
    "check": "tsc"
  }
```

**Comment by TheMaximeBatandeoExperience** [comment]
Thank you ! I have done that it worked. Actually I was pursuing the investigation and it seems that the slowing starting process occurs when I use GraphQL Mutation operations. With Typescript operations of GraphQL Queries it is fast (<1 min). But for each GraphQL Mutation, it takes 6 minutes to register by the GraphQL handler.
