### ISSUE TITLE
Feedback for “Backend for Frontend (BFF) Pattern for GraphQL APIs”

### ISSUE THREAD

**Issue by Warxcell** [wundergraph/wundergraph#1398]
How is N+1 in weather_getCityByName solved?

How to apply composition for mutations?

For example there is service A and services B - service A contains database of queustions. Service B acts like storage for users' answers. Fo when user answers questionnaire - gateway must collect data from service A, merge it with user input and pass it to service B?

How to DRY _join ? For example you could have different queries that joins same thing?

**Comment by viktorgt** [comment]
This use case is actually the primary reason we're currently researching BFF. I read the [data loader](https://wundergraph.com/blog/dataloader_3_0_breadth_first_data_loading) blog post, but from what I understand, it relies solely on GraphQL. How would it handle a REST API where I need to perform a join?
