### ISSUE TITLE
[Issue]: Server side Caching does not work from the cURL

### ISSUE THREAD

**Issue by HussainLatiff** [wundergraph/wundergraph#1404]
### Description

Caching works when using the React UI and refreshing the same operation as seen in the below image where the time taken goes down to about 1 ms 
![image](https://github.com/user-attachments/assets/7ab99dab-912f-4d0d-85db-d1d9f2511580)

But when copying the cURL and importing in POSTMAN and running the exact same query the caching does not really boost performance, we have an average of about 500-300+ ms

<img width="864" alt="image" src="https://github.com/user-attachments/assets/2f6388c6-d7f7-4924-b273-12c8471f5bbd">

### Reproduction

1. Run  npx create-wundergraph-app ProjectName and clone the caching repo.
2. Run npm start on the terminal.
3. Test the performance by refreshing the query in that pops up on localhost:3000.
4. Open the network tab and copy the cURL and Import into POSTMAN.
5. Run the GET request on POSTMAN.

**Comment by RayHughes** [comment]
Is postman configured to respect cache browser cache headers? I recommend utilizing edge caching if your able to.
