### ISSUE TITLE
@transform Directive failed

### ISSUE THREAD

**Issue by AnsonCode** [wundergraph/wundergraph#166]
### Bug description

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/20960032/188453402-b2755cd2-aa23-4140-b964-66f8d4d3bbe2.png">

### How to reproduce

```gql
query MyQuery($code: ID!, $name: String! @internal) {
  countries_country(code: $code) {
    code
    capital @export(as: "name")
    emoji
    name
    weather: _join @transform(get: "weather_getCityByName.weather") {
      weather_getCityByName(name: $name) {
        weather  {
          temperature {
            actual
            feelsLike
          }
        }
      }
    }
  }
}
```

### WunderGraph information

```ts
const weather = introspect.graphql({
  apiNamespace: 'weather',
  url: 'https://graphql-weather-api.herokuapp.com/',
});

const countries = introspect.graphql({
  apiNamespace: 'countries',
  url: 'https://countries.trevorblades.com/',
});
```

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```
111d0c4b05b41c75fc76b3ad23be691582506d5a
```

**Comment by jensneuse** [comment]
Transform doesn't work in the playground, but should work when creating Operations like the regular way. Can you check?

**Comment by AnsonCode** [comment]
OK，I've checked it .And It worked!
<img width="369" alt="image" src="https://user-images.githubusercontent.com/20960032/188459843-fb83f5d6-c5fd-476c-abb6-27687c077a84.png">
