### ISSUE TITLE
[docs] Comparison to PostGraphile

### ISSUE THREAD

**Issue by 205g0** [wundergraph/wundergraph#215]
## Problem

I liked the comparison to Hasura which gave me a better understanding. Now, I'd like to have one PostGraphile. Why should I use wundergraph instead and/or next to Postgraphil?

**Comment by Slickstef11** [comment]
@205g0 This is a great idea. Added to the backlog!

**Comment by Slickstef11** [comment]
@205g0 Have you thought of contributing this yourself? Would love to see what you come up with.

**Comment by Faizan711** [comment]
is this issue still open, if so then i would like to be assigned for it.

**Comment by jensneuse** [comment]
> is this issue still open, if so then i would like to be assigned for it.

Yes sure, go ahead and raise a PR.

**Comment by Pagebakers** [comment]
@Faizan711 Are you still working on this? Would love to see it!

**Comment by Faizan711** [comment]
Yes, i am but finding difficulty to arrange the required information, can you please help me?

**Comment by Slickstef11** [comment]
> Yes, i am but finding difficulty to arrange the required information, can you please help me?

@Faizan711 I can help you. Are you in our Discord? If not, Join: https://discord.gg/cnRWwHXbQm and ping me @stefan-wundergraph

**Comment by Faizan711** [comment]
No i wasn't on your Discord, i will join and then ping you.

**Comment by Faizan711** [comment]
This issue can be closed now.
