### ISSUE TITLE
Add transformer to extract an item out of a list.

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#25]
## Problem
It is often the case that an API has an interface for performing an operation over multiple items, however the user of the API would like to offer an operation that operates over a single item.

An example is a delete item operation. Imagine a theoretical API:

`DELETE www.example.com/api/v1/items?ids=[12,43,4]`

Which returns a list of ids.

But we want to offer a Wundergraph operation `deleteItem(id: int)`

At the moment, I need to do some mangling in the hooks to convert the return type, which means I cannot use the typed helpers, and the transformation is not happening in the fast go codebase.

## Suggested solution

Add a transformer to allow extraction of an indexed item from a returned list.

maybe `@transform(index: 0)`

Where "index" is the transformation over a list type item that converts it to a single item. The argument it the 0-based position of the item.

The resulting type would need to be nullable because the item at the index may not exist.

## Alternatives

The alternative it to use a mutatingPostResolve hook, but this is less desirable for the reasons stated above.

**Comment by jensneuse** [comment]
Have you tried something like this:
`www.example.com/api/v1/items?ids=[{id}]`
I think this should work.
As an alternative, I think it would be interesting to have a directive like `@transform(list: {index: 0}}` or similar.

**Comment by greemo** [comment]
Yeah, I can call the API no problem, with the following operation definition:

mutation deleteItem($id: Int!) {
    object: ns_deleteItems(ids : [$id]) {
        id
    }
}

but the result type is a list, which needs to be unpacked somehow to the single item.

**Comment by jensneuse** [comment]
I think I like your idea of adding `@transform(index: 0)`.
Do you need guidance on how to add it?

**Comment by greemo** [comment]
I'll start by setting up my dev environment for the codebases, and creating a unit test for the go part of the code. If I have any issues, I'll PM you on Discord.
