### ISSUE TITLE
Improve wunderctl generate error messages to aid in debugging

### ISSUE THREAD

**Issue by rupurt** [wundergraph/wundergraph#262]
### Bug description

When I run `wunderctl generate` I receive an error. The message is not particularly helpful for debugging. Can this include the file and line number so I know where to start looking for the `empty data variable`?

```bash
> wunderctl generate
Couldn't configure your WunderNode: Error: could not resolve empty data variable: undefined
Error: configuration could not be generated. Process exit with code 1
2022-10-16T07:25:47-07:00       error   Script runner exited with error {"runnerName": "config-runner", "exit": 1, "startTs": 1665930347155262000, "stopTs": 1665930347457188000, "complete": true}
```

### Environment & setup

- OS: Mac OS
- Go version: go version go1.18 darwin/arm64
- Database: PostgreSQL
- Node.js version: v17.6.0

### WunderCtl Version

```
Version: 0.111.4
Commit: 4e9eb8f7500fa37afa524890cae122cf801033b9
Date: 2022-10-10T17:58:54Z
BuiltBy: ci
```

resolve: ENG-808

**Comment by jensneuse** [comment]
Can you share your wundergraph.config.ts?
Even with tracing, which I agree is worth adding, it might be hard to help without seeing the config.

**Comment by rupurt** [comment]
@jensneuse I resolved the problem myself but I opened this issue as a quality of life improvement for those in the future. I feel like the CLI should print the variable name + source file + line number. Currently it just prints the value of the variable which isn't very helpful.

FWIW: The problem was an environment variable that was not set 😄

**Comment by jensneuse** [comment]
> @jensneuse I resolved the problem myself but I opened this issue as a quality of life improvement for those in the future. I feel like the CLI should print the variable name + source file + line number. Currently it just prints the value of the variable which isn't very helpful.
> 
> FWIW: The problem was an environment variable that was not set 😄

Cool, thank you for reporting. We'll have a look at how we can improve the messaging around env variables. You definitely have a point here.
