### ISSUE TITLE
wunderctl generate hangs when run inside a docker build

### ISSUE THREAD

**Issue by rupurt** [wundergraph/wundergraph#263]
### Bug description

`RUN wunderctl generate` inside a docker image hangs until a timeout when trying to generate the prisma engines

### How to reproduce

Cross posted from https://github.com/wundergraph/docker/issues/2

### Expected behavior

`wunderctl generate` completes in a reasonable amount of time

### Environment & setup

- OS: Mac OS, Windows, Debian, CentOS
- Go version: go version go1.18 darwin/arm64
- Database: PostgreSQL
- Node.js version: v18.11.0

### WunderCtl Version

```
Version: 0.111.4
Commit: 4e9eb8f7500fa37afa524890cae122cf801033b9
Date: 2022-10-10T17:58:54Z
BuiltBy: ci
```

**Comment by Pagebakers** [comment]
Closing this in favor of https://github.com/wundergraph/docker/issues/2
