### ISSUE TITLE
OpenID Connect provider, oidc.login.xyz, is returning: `Unrecognised client id.` or `Bad query params`

### ISSUE THREAD

**Issue by John-Appleseed** [wundergraph/wundergraph#283]
### Bug description

OpenID Connect provider, oidc.login.xyz, is returning. `Unrecognised client id.` or `Bad query params`

### How to reproduce

Created a new client id with Login.xyz 
```sh
curl -X POST https://oidc.signinwithethereum.org/register \
   -H 'Content-Type: application/json' \
   -d "{\"redirect_uris\": [\"backend.example.com\"]}"
```
Save variables to .env file
```bash
login_xyz_issuer="https://oidc.login.xyz/"
login_xyz_client_id="$login_xyz_client_id" # from curl response
login_xyz_client_secret="$login_xyz_client_secret" # from curl response
login_xyz_redirect_uri="https://backend.example.com" 
```
Configured cookieBased authProviders.openIdConnect to wundergraph.config.ts
```js
  authProviders.openIdConnect({
    id: 'loginxyz',
    issuer: new EnvironmentVariable('login_xyz_issuer'),
    clientId: new EnvironmentVariable('login_xyz_client_id'),
    clientSecret: new EnvironmentVariable('login_xyz_client_secret'),
  }),
],
authorizedRedirectUris: [
  new EnvironmentVariable('login_xyz_redirect_uri'),
]
secureCookieHashKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_HASH_KEY'), // must be of length 32
secureCookieBlockKey: new EnvironmentVariable('WUNDERGRAPH_SECURE_COOKIE_BLOCK_KEY'), // must be of length 32
csrfTokenSecret: new EnvironmentVariable('WUNDERGRAPH_CSRF_TOKEN_SECRET'), // must be of length 11
```
Test cookie auth with curl
```sh
curl https://backend.example.com/app/main/auth/cookie/authorize/loginxyz?redirect_uri=https://backend.example.com
```
```html
<a href="https://oidc.login.xyz/authorize?client_id=9445e4ff-2bda-4b8d-8b1b-a9f40a52c133&amp;redirect_uri=http%3A%2F%2Fbackend.example.com%2Fapp%2Fmain%2Fauth%2Fcookie%2Fcallback%2Floginxyz&amp;response_type=code&amp;scope=openid+profile+email&amp;state=O1MDVfjSc35vvMdevV00sQ">Found</a>.
```
Following the link will return:
```sh
Bad query params
```
Test cookie auth with browser
```sh
Unrecognised client id.
```

### Expected behavior

Successful authentication.

### WunderGraph information

wundergraph.config.ts - within the steps to reproduce
wundergraph.operations.ts - default
wundergraph.server.ts - default

### Environment & setup

- OS: Gentoo Linux
- Go version: go version go1.19.2 linux/amd64
- Database: MongoDB
- Node.js version: v18.6.0

### WunderCtl Version

Version: 0.109.1
Commit: 738ee0e28390be27adfbe0533216c407057f7f0a
Date: 2022-09-15T21:53:21Z
BuiltBy: ci

**Comment by jensneuse** [comment]
Assuming that "app" is your application name, and "localhost:9991" is your WunderNode endpoint, you can start the login flow on "http://localhost:9991/app/main/auth/cookie/authorize/loginxyz".

The login flow is started from the WunderNode. Once successful, the cookie will be set.

Your config looks right.

**Comment by John-Appleseed** [comment]
`login_xyz_redirect_uri` had to have `http://` URI rather than a `https://` URI.

Fixed
```
login_xyz_redirect_uri="http://backend.example.com" 
```
