### ISSUE TITLE
Blog links are broken

### ISSUE THREAD

**Issue by piyush-multiplexer** [wundergraph/wundergraph#29]
### Bug description

Two of links in RECENT POSTS section(2022) are not working due to **/blog** is being repeated twice, and redirected to 404.

https://wundergraph.com/blog/blog/partnership_announcement_oracle_cloud_and_wundergraph
https://wundergraph.com/blog/blog/keycloak_integration_in_minutes_with_cloud_IAM_and_wundergraph

### How to reproduce

![image](https://user-images.githubusercontent.com/18528418/172361671-8a798301-0d57-43f1-9591-158ef102d4d4.png)

### Expected behavior
It should redirected to related post page with single /blog route.

**Comment by Slickstef11** [comment]
Hey @piyush-multiplexer thank you for reporting this bug! It's been fixed now.
