### ISSUE TITLE
🐛 Getting Started missing important information

### ISSUE THREAD

**Issue by hinogi** [wundergraph/wundergraph#34]
### Bug description

https://wundergraph.com/docs/guides/your_first_wundergraph_application/overview out of date, missing information like where to execute wunderctl

### How to reproduce

1. npm i -g @wundergraph/wunderctl@latest
2. mkdir test-wundergraph && cd test-wundergraph
3. wunderctl init
4. npm install
5. wunderctl add wundergraph/weather wundergraph/countries
6. Open the file wundergraph.config.ts to adjust the configuration.
7. wunderctl generate <-- Error

### Expected behavior

Hint the reader to change the folder to .wundergraph or make the wunderctl search in .wundergraph

### WunderGraph information

https://wundergraph.com/docs/guides/your_first_wundergraph_application/overview

### Environment & setup

- OS: OS: Windows 10 10.0.19044
- Node.js version:  16.13.1

### WunderCtl Version

```
Version: 0.90.32
Commit: 386a3d4b66204411dc89da6919aad0bebe524657
Date: 2022-06-06T12:22:22Z
BuiltBy: ci
```

**Comment by cwmoss** [comment]
`cd .wundergraph` solves this problem with `generate`

next error will be on step `wunderctl up --debug`

```
error	watcher	{"watcher": "wundergraph config", "error": "lstat generated/wundergraph.config.json: no such file or directory"}
...
Could not load wundergraph.config.json. Did you forget to run `wunderctl generate` ?
```

indeed there is no such file :(

**Comment by cwmoss** [comment]
ok. i got it running. i had to modify `wundergraph.config.ts` i could successfully connect a sqlite db and define a query like: `http://localhost:9991/app/main/operations/Posts?condition={%22title%22:{%22startsWith%22:%22Hello%22}}`

i still have a hard time to "get it". i have a question: when running in production with the go server, is the sqlite process part of the go server? or is it running in some "shadow" node-js/prisma server?

**Comment by jensneuse** [comment]
There's a Go server (gateway) and a NodeJS server (hooks). If you're connecting to a database, the Go server spawns a prisma process and talks to it over HTTP. In theory, it would be possible to compile prisma to a shared object and load it from go directly. Then the gateway can talk to it in memory. However, this does not work on all systems, e.g. Windows doesn't work, but it could be enabled without many changes, at least on linux for production environments.

**Comment by cwmoss** [comment]
hi jens,
thank you for your reply. i think i can see it much clearer now what is happening "under the hood" :) i actually read the text "vs_hasura" that explained it quite good. maybe it is more concise to say: hasura at its core is a graphql to sql interpreter where wundergraph is a graphql to rest compiler and request/api router/gateway...
