### ISSUE TITLE
Generated Nextjs starter out of date.

### ISSUE THREAD

**Issue by Pagebakers** [wundergraph/wundergraph#36]
### Bug description

I was having issues getting the Nextjs starter running, it turns out the code generated was out of date.

```ts
import {
    AuthProviders,
    useLiveQuery,
    useWunderGraph,
    withWunderGraph,
} from '../components/generated/wundergraph.nextjs.integration';
```

Should be

```ts
import {
    AuthProviders,
    useLiveQuery,
    useWunderGraph,
    withWunderGraph,
} from '../components/generated/nextjs';
```

But when looking at the source, this is looking up to date, so I'm not sure where the issue lies.

https://github.com/wundergraph/wundergraph/blob/main/packages/nextjs-testapp/pages/authentication.tsx

### How to reproduce

1. Install wunderctl with npm
```
npm i -g wunderctl
```

3. Run 
```
wunderctl init --template nextjs-starter -o /some/path
```

### Expected behavior

The app should run without errors.

### WunderGraph information

All default

### Environment & setup

MacOS m1
Node 14

### WunderCtl Version

```
Version: 0.90.32
Commit: 386a3d4b66204411dc89da6919aad0bebe524657
Date: 2022-06-06T12:25:36Z
BuiltBy: ci
```

**Comment by StarpTech** [comment]
Hi @Pagebakers thank you for opening an issue. I fixed the places in https://github.com/wundergraph/wundergraph/commit/08493955ce6a3d96c23b7bb07ccf788ca8911752
