### ISSUE TITLE
Example WG repo is still broken due to missing folder

### ISSUE THREAD

**Issue by bmcilw1** [wundergraph/wundergraph#361]
### Bug description

The [nextjs-postgres-prisma](https://github.com/wundergraph/wundergraph/tree/main/examples/nextjs-postgres-prisma) still does not run without errors with the latest WG install.

This is due to the `components` folder not being created by default.

### How to reproduce

1. Clone this repo into a clean new project, the official [wg repo](https://github.com/wundergraph/wundergraph)
2. Navigate to the `nextjs-postgres-prisma` repo
3. Run `npm install`
4. Run `npm start`

View error due to missing client.

### Expected behavior

- WG examples should all build and run on stable versions. Opportunity for a CI check?
- WG should create any folders that it needs in order to successfully create the generated SDKs

### WunderGraph information

See this repo

### Environment & setup

- OS:  Mac OS
- Go version: 
- Database: 
- Node.js version:  node v16.18.1

### WunderCtl Version

    "@wundergraph/nextjs": "^0.5.0",
    "@wundergraph/sdk": "^0.123.0",

**Comment by Pagebakers** [comment]
Thanks for reporting @bmcilw1 we've reproduced it and are looking into a fix.

**Comment by Pagebakers** [comment]
@bmcilw1 We just merged a fix in main, I'm closing the issue, but feel free to open it again in case you have issues.
