### ISSUE TITLE
Typescript/Javascript SDK is not passing through the error 

### ISSUE THREAD

**Issue by robbydooo** [wundergraph/wundergraph#364]
### Bug description

When the server returns an invalid input error response, the SDKs for Typescript and possible others (I havent checked) always return the hardcoded error "Response is not ok" instead of the exact error`

### How to reproduce

-Provide an invalid datatype to any mutation.
- Run via SDK
- Server will return an error response with json containing the error type.
- SDK will only report "response is not ok"

### Expected behavior

Expected error response in SDK (example):
```
{"Message":"Bad Request: Invalid input","Input":{},"Errors":[{"propertyPath":"/","invalidValue":{},"message":"\"ids\" value is required"},{"propertyPath":"/","invalidValue":{},"message":"\"countryId\" value is required"}]}
```

actual 
```
"Response is not ok"
```

### WunderGraph information

Not relevant

### Environment & setup

- OS: Any
- Go version: Any
- Database: Any
- Node.js version: 18 - Any

### WunderCtl Version

```
0.123
```

**Comment by jensneuse** [comment]
Thank you @robbydooo, we'll look into this.

**Comment by Pagebakers** [comment]
@robbydooo We introduced a new InputValidationError type that is returned in the client and React hooks, so the errors are accessible now.

See: https://docs.wundergraph.com/docs/clients-reference/typescript-client#input-validation-error
