### ISSUE TITLE
🐛 [GitPod] Network error in graphiql when trying to load schema 

### ISSUE THREAD

**Issue by hinogi** [wundergraph/wundergraph#37]
### Bug description

![image](https://user-images.githubusercontent.com/4602609/172877125-36e2fab5-cd5e-4984-a012-4714f5bfcd76.png)

### How to reproduce

1. https://gitpod.io/#https://github.com/wundergraph/wundergraph
2. go to gitpod /app/main/graphql
3. try to open the docs explorer

### Expected behavior

docs explorer should show the schema

### WunderGraph information

https://gitpod.io/#https://github.com/wundergraph/wundergraph

### Environment & setup

https://gitpod.io/#https://github.com/wundergraph/wundergraph

### WunderCtl Version

https://gitpod.io/#https://github.com/wundergraph/wundergraph

**Comment by StarpTech** [comment]
@hinogi, please retry. The examples have been involved a lot. It works on my end.
