### ISSUE TITLE
Getting "TypeError: (0 , swr_1.default) is not a function" on useUser function

### ISSUE THREAD

**Issue by ayoubmoussaid** [wundergraph/wundergraph#379]
### Bug description

I got this error:
```
error - TypeError: (0 , swr_1.default) is not a function
    at useUser (C:\Users\User\Desktop\wundergraph\wundergraph\examples\keycloak-oidc-authentication\node_modules\@wundergraph\swr\dist\hooks.js:142:34)
    at Home (webpack-internal:///./pages/index.tsx:12:87)
```
![image](https://user-images.githubusercontent.com/45740145/204322320-a23ea2cc-611c-41f8-bacb-2e45c0b55faa.png)

when I try to run the default example for keycloak-oidc-authentication. I only changed the env file.

### How to reproduce

Just run the example as it is right now, the issue should be there! Unless I am doing something wrong.

### WunderGraph information

I have everything as default .. because I run the example directly from the repository. I only changed .env file!

### Environment & setup

- OS: windows
- Database: PostgreSQL
- Node.js version: v16.17.0

### WunderCtl Version

```
Version: 0.118.1
```

**Comment by Pagebakers** [comment]
Thanks for reporting @ayoubmoussaid we're currently verifying the examples.

Installing SWR should resolve it.

```
npm i swr@2.0.0-rc.3
```

**Comment by Pagebakers** [comment]
All examples should now be up to date, thanks again for reporting!
