### ISSUE TITLE
Memory leak when contiune update config file which wunderctl started by up command

### ISSUE THREAD

**Issue by javacode123** [wundergraph/wundergraph#394]
### Bug description

1: use cmd start server:
wunderctl --debug true --wundergraph-dir wundergraph/examples/simple/.wundergraph
2: update wundergraph.config.json
3: use memory continue increase
4: i think this is because NewInMemory continue apply memory but not relase

### Environment & setup

- OS:  mac os
- Go version:  go version go1.19 darwin/arm64
- Database: 
- Node.js version: 

### WunderCtl Version

```

```
commit: be612bb

**Comment by javacode123** [comment]
`func NewInMemory(maxSize int64) (*InMemoryCache, error) {
	inMemoryCache, err := ristretto.NewCache(&ristretto.Config{
		NumCounters: maxSize / 10,
		MaxCost:     maxSize,
		BufferItems: 64,
	})
	if err != nil {
		return nil, err
	}
	return &InMemoryCache{
		c: inMemoryCache,
	}, nil
}`
it will continuse apply memory when config.json changes, i thik we should release it

**Comment by StarpTech** [comment]
Hi @javacode123 thank you for opening an issue. We will take a look at it asap.

**Comment by fiam** [comment]
@javacode123 Thanks a lot for your report. We've reproduced the problem and identified a problem in our usage of [`ristretto`](https://github.com/dgraph-io/ristretto). We'll have a fix ready tomorrow.

**Comment by javacode123** [comment]
thx, could please add the pr when you fix this problem. i want to learn how to fix it

**Comment by fiam** [comment]
@javacode123 We were missing a call to [ristretto.Cache.Close](https://pkg.go.dev/github.com/dgraph-io/ristretto?utm_source=godoc#Cache.Close). See #401 for the whole PR. If you have any questions about it, we're more than happy to help.
