### ISSUE TITLE
Native type Blob is not compatible with declared field type String, expected field type Bytes.

### ISSUE THREAD

**Issue by lovestaryouth** [wundergraph/wundergraph#402]
### Bug description

normal mysql connection is right, but when exists column with type of 'Blob', will appear error

### How to reproduce

1. Go to 'pkg.datasources.database.engine.go'
2. See code 'dataModel := strings.Replace(response.Result.DataModel, " Bytes", " String", -1)'
3. I want to know that the block code why to use, please

### Environment & setup

- OS: Mac OS
- Go version: 1.19
- Database: MySQL
- Node.js version: v18.8.0

### WunderCtl Version

```

```

**Comment by Slickstef11** [comment]
@lovestaryouth Thanks for reporting. We will be taking a look at this.

**Comment by Pagebakers** [comment]
We currently don't support this, but would be very happy if you can open PR to fix this!

**Comment by Pagebakers** [comment]
We've added this to the roadmap, so closing the issue here. 

We would still love the receive a PR for the implementation 🙏
