### ISSUE TITLE
The generated uploadFiles method should be accessible for unauthorized users.

### ISSUE THREAD

**Issue by erguotou520** [wundergraph/wundergraph#455]
## Problem
When upload files using the generated nextjs code, it returns an `csrf` empty issue while not logged in.

## Suggested solution
The generated uploadFiles should be accessible for anonymous users. 

## Alternatives
Or this behavior can be configurable.

## Additional context

Discord discussion here: https://discord.com/channels/738739428314316823/896556567753789460/1052126195963142195

**Comment by Pagebakers** [comment]
Thanks for reporting @erguotou520 we will be releasing the advanced s3 uploads RFC soon, which gives you more controls over authorizing uploads.

**Comment by fiam** [comment]
This has been fixed in #646
