### ISSUE TITLE
Failed to use Postgraphile as a graphql datasource

### ISSUE THREAD

**Issue by minhdtb** [wundergraph/wundergraph#46]
### Bug description

an error occurred and the code could not be generated

only working with option `--skip-plugins graphile-build:NodePlugin`

### How to reproduce

run postgrapgphile

```
postgraphile -c 'postgres://storeo:storeo@localhost:5433/storeo' --watch --enhance-graphiql --dynamic-json
```

setup datasource
wundergraph.config.ts
```ts
const postgraphile = introspect.graphql({
    apiNamespace: 'pg',
    url: 'http://localhost:5000/graphql'
})

const myApplication = new Application({
    name: 'app',
    apis: [
        postgraphile
    ],
});
```

run wunderctl
```
wunderctl generate  --env .env
```

error
```
2:58:38 PM: wundergraph.app.schema.graphql updated
Error: Interface field pg_Node.nodeId expected but Query does not provide it.
    at assertValidSchema (/home/minhdtb/projects/storeo/storeo-backend/node_modules/graphql/type/validate.js:59:11)
    at validate (/home/minhdtb/projects/storeo/storeo-backend/node_modules/graphql/validation/validate.js:63:35)
    at Object.enter (/home/minhdtb/projects/storeo/storeo-backend/node_modules/@wundergraph/sdk/dist/graphql/operations.js:47:59)
    at visit (/home/minhdtb/projects/storeo/storeo-backend/node_modules/graphql/language/visitor.js:197:21)
    at parseOperations (/home/minhdtb/projects/storeo/storeo-backend/node_modules/@wundergraph/sdk/dist/graphql/operations.js:30:29)
    at /home/minhdtb/projects/storeo/storeo-backend/node_modules/@wundergraph/sdk/dist/configure/index.js:350:61
    at processTicksAndRejections (node:internal/process/task_queues:96:5)





--->
No Operations found! Please create at least one Operation in the directory ./operations
Operation files must have the file extension '.graphql', otherwise they are ignored.
Operations don't need to be named, the file name is responsible for the operation name.
<---

```

### Expected behavior

working as expected

### WunderGraph information

N/A

### Environment & setup

OS: Ubuntu
Go version: go1.17.2 linux/amd64
Database: PostgreSQL
Node.js version: v16.15.1

### WunderCtl Version

```
Version: 0.90.32
Commit: 386a3d4b66204411dc89da6919aad0bebe524657
Date: 2022-06-06T12:21:43Z
BuiltBy: ci

```

**Comment by jensneuse** [comment]
I think we should build a postgraphile example and figure out the issues you're facing here. I know there are a few quirks with graphile and the Node interface, but it's solveable.

**Comment by abdelhameedhamdy** [comment]
I already used postgraphile with WG few months ago  without issue.

**Comment by minhdtb** [comment]
@abdelhameedhamdy Could you share some sample? I have tried the latest version but still not working. And the postgraphile subscriptions feature also doesn't work even with the option `-skip-plugins graphile-build:NodePlugin `

**Comment by abdelhameedhamdy** [comment]
> @abdelhameedhamdy Could you share some sample? I have tried the latest version but still not working. And the postgraphile subscriptions feature also doesn't work even with the option `-skip-plugins graphile-build:NodePlugin `

Sorry for late reply, it just works as you did, postgraphile endpoint exposed from cli, url endpoint data source is added in WG config file, simple as that. 
I don't recall the used WG version.

**Comment by jensneuse** [comment]
@minhdtb as an alternative, could you directly connect to PostgreSQL using `introspect.postgres`?

**Comment by minhdtb** [comment]
@jensneuse I want to use custom query feature of postgraphile by using plpgsql function. So I used postgraphile as a datasource. Currently, if postgraphile's custom query returns a JSON data type, wundergraph won't get it. According to the document here [url](https://wundergraph.com/docs/guides/strategies/using_json_columns_with_a_custom_graphql_schema),  I see that replaceJSONTypeFields only support db datasource, I think this feature is needed for graphql datasource as well

**Comment by jensneuse** [comment]
> @jensneuse I want to use custom query feature of postgraphile by using plpgsql function. So I used postgraphile as a datasource. Currently, if postgraphile's custom query returns a JSON data type, wundergraph won't get it. According to the document here [url](https://wundergraph.com/docs/guides/strategies/using_json_columns_with_a_custom_graphql_schema), I see that replaceJSONTypeFields only support db datasource, I think this feature is needed for graphql datasource as well

That's great feedback. I think it makes sense to add this feature to all data sources.

**Comment by Knorway** [comment]
I'm having the same issue with integrating postgraphile and really hope to use wundergraph with it. is there any plan to solve this if i may ask?

**Comment by wluxion** [comment]
Same issue at the original poster. And I'm only trying PostGraphile because postgres introspection has an ambiguous `Invalid string length at JSON.stringify (<anonymous>) at fashHash` error with my database schema.
