### ISSUE TITLE
create-wundergraph-app fails with `Error: Cannot find module 'dotenv'`

### ISSUE THREAD

**Issue by TzviPM** [wundergraph/wundergraph#482]
### Bug description

When trying to follow the getting started instructions on https://docs.wundergraph.com/getting-started, `create-wundergraph-app` is unsuccessful.

### How to reproduce

1. run `npx create-wundergraph-app my-project -E simple`
2. observe error: `Error: Cannot find module 'dotenv'`

### Expected behavior

A minimal wundergraph project should be created

### WunderGraph information

N/A

### Environment & setup

- OS: Mac OS Monterey 12.6.1
- Go version: go version go1.19.4 darwin/arm64
- Database: N/A
- Node.js version: v19.0.0

### WunderCtl Version

N/A

**Comment by fiam** [comment]
Thanks for the heads up @TzviPM - We're working on a fix

**Comment by fiam** [comment]
@TzviPM We've just released a fix. Thanks for your help!

**Comment by TzviPM** [comment]
Wow, that was fast; thank you! I can confirm that it is now WAI.
