### ISSUE TITLE
Got 403 response when run mutation with oidc

### ISSUE THREAD

**Issue by javacode123** [wundergraph/wundergraph#484]
### Bug description

i run auth0-oidc-authentication demo and add two oerations. the one is quey, the one is mutation
`{
	local_mysql_findFirstpet() {
		age
		name
	}
}
mutation ($name: String) {
	local_mysql_createOnepet(data: { name: $name }) {
		name
		id
	}
}
`
i use http method run this two request. quey is successfully. but mutation got 403.
![image](https://user-images.githubusercontent.com/11720169/209077686-354a0c99-ce74-48d1-9fe2-fda37fba578a.png)
if i remove cookie it will work successfully「if i add auth for this operation, it will ruturn 401」
![Uploading image.png…]()

### How to reproduce

1. Go to  auth0-oidc-authentication project
2. add operation 
`mutation ($name: String) {
	local_mysql_createOnepet(data: { name: $name }) {
		name
		id
	}
}
`
4. Run http post with cookie
5. See error

### Environment & setup

- OS: mac
- Go version: 1.8
- Database: Mysql
- Node.js version: 

### WunderCtl Version

```

```
the lastest

**Comment by jensneuse** [comment]
Fixed by acquiring a csrf token according to the spec: https://docs.wundergraph.com/docs/architecture/wundergraph-rpc-protocol-explained#csrf-protection

**Comment by javacode123** [comment]
@jensneuse could i use config to skip csrf
