### ISSUE TITLE
[Example] How to use ory kratos with wundergraph

### ISSUE THREAD

**Issue by a0v0** [wundergraph/wundergraph#49]
Please add an example showcasing how to setup ory kratos login/signup with wundergraph

**Comment by a0v0** [comment]
can I expect a working demo within this month?

**Comment by jensneuse** [comment]
It depends. Are you interested in becoming a customer of our support plans this month? We're not making commitments of any sort to non-customers. So if you're not a customer, please be patient. We're investing heavily into open source, but this doesn't mean that we're doing this for free. We have to build and sustain a business too. Please don't demand features or demos if you're not a paying customer. It's not the right kind of behavior towards a company that invests into open sourcing. Thank you.
