### ISSUE TITLE
Neon Serverless Driver for Postgres

### ISSUE THREAD

**Issue by jozef-slezak** [wundergraph/wundergraph#506]
## Problem

I would  like to depliy wundergraph to cloudflare workers and dint know how to switch the postgres driver. Maybe you could provide docs for that.

# Solution

Pg driver over websocket for edge described here
https://neon.tech/blog/serverless-driver-for-postgres/

**Comment by jensneuse** [comment]
WunderGraph is written in Go and is built in a way that's not compatible with cloudflare workers. Cloudflare workers is a very limited runtime as it's simply v8 isolates with a proprietary API. WunderGraph requires a Linux/Mac/windows environment. This means, you can use any regular Postgres client or even the native postgres integration of WunderGraph. You can deploy on WunderGraph cloud or any docker compatible runtime.
