### ISSUE TITLE
React Query's live query is not typed properly

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#518]
### Bug description

The return type of `useQuery` using `@wundergraph/react-query` is incomplete. Using the [nextjs-react-query](https://github.com/wundergraph/wundergraph/blob/473653f5510326d04078b12eef5a5bed42285279/examples/nextjs-react-query) example, if we modify the [useQuery lines](https://github.com/wundergraph/wundergraph/blob/main/examples/nextjs-react-query/pages/index.tsx#L5-L7) to the following:

```ts
	const {data, isSubscribed } = useQuery({
		operationName: 'Dragons',
		liveQuery: true,
                enabled: true,
	});
```
TypeScript will complain that `Property 'isSubscribed' does not exist on type 'UseQueryResult<DragonsResponseData, GraphQLResponseError>` (but I can console it normally).

Also I have some feedback on the API. It took me a while to figure this out, but it seems I have to set both `liveQuery` and `enabled` to true. It means that the following code

```ts
	const {data, isSubscribed } = useQuery({
		operationName: 'Dragons',
		liveQuery: true,
	});
```
will not enable live query (I think because of [this line](https://github.com/wundergraph/wundergraph/blob/473653f5510326d04078b12eef5a5bed42285279/packages/react-query/src/hooks.ts#L98) where `options.enabled` is `undefined` by default). This is a bit counter-intuitive. I think you guys should set `enabled` to true by default.

### How to reproduce

See above

### WunderGraph information

N/A

### Environment & setup

```
@wundergraph/react-query v0.2.4
```

### WunderCtl Version

```
0.125.0
```

**Comment by jensneuse** [comment]
cc @Pagebakers

**Comment by Pagebakers** [comment]
This will be fixed in the next release, later this week.
