### ISSUE TITLE
when user @export + @internal query meet err

### ISSUE THREAD

**Issue by javacode123** [wundergraph/wundergraph#521]
### Bug description

when user @export + @internal query meet err and can not genenerate operation

### How to reproduce

1: use mysql as datasource, space_name: aigc
```
CREATE TABLE `Creation` (
  `id` int NOT NULL AUTO_INCREMENT,
  `authorId` int NOT NULL,
  `args` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `createdAt` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `Creation_authorId_fkey` (`authorId`),
  CONSTRAINT `Creation_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `AppUser` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `ArtWork` (
  `id` int NOT NULL AUTO_INCREMENT,
  `creationId` int NOT NULL,
  `url` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `isDraft` tinyint(1) NOT NULL DEFAULT '1',
  `published` tinyint(1) NOT NULL DEFAULT '0',
  `publishAt` datetime(3) DEFAULT NULL,
  `likeCount` int NOT NULL DEFAULT '0',
  `recommendRate` int NOT NULL DEFAULT '0',
  `sharedCount` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ArtWork_creationId_fkey` (`creationId`),
  CONSTRAINT `ArtWork_creationId_fkey` FOREIGN KEY (`creationId`) REFERENCES `Creation` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=26 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```
2:  query, which means, query all creation, each creation contain total artwork, and first artwork info
```
query GetMyDrafts( $creationId: Int @internal) {
  data: aigc_findManyCreation(orderBy: {createdAt: desc}) {
    id @export(as: "creationId")
    _count {
      ArtWork
    }
    _join {
      aigc_findFirstArtWork(where: {creationId: {equals: $creationId}}) {
        url
      }
    }
  }
}
```
3: query meet err
![image](https://user-images.githubusercontent.com/11720169/211199514-14b01964-be91-4780-9e1c-d4fbe10e7523.png)
![image](https://user-images.githubusercontent.com/11720169/211199524-80b12320-2a23-4ffb-8535-cb1ac6d39f3a.png)
4: alse can not generate opertaion
![image](https://user-images.githubusercontent.com/11720169/211199583-2e9de47d-7d26-49f2-a35d-e90c573d0bab.png)

### WunderGraph information

wundergraph commit: 193b974e

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 
 

### WunderCtl Version

```

```
wundergraph commit: 193b974e

**Comment by Slickstef11** [comment]
Got it. Thank you for reporting!

**Comment by javacode123** [comment]
hi, i want to know when will fix it

**Comment by StarpTech** [comment]
Hi @javacode123 would you like to create a PR? We don't make any promises about when OSS issues will be fixed. If you need it faster you contact us for an enterprise contract https://wundergraph.com/contact/sales

**Comment by javacode123** [comment]
> Hi @javacode123 We don't make any promises about when OSS issues will be fixed. If you need it faster you contact us for an enterprise contract https://wundergraph.com/contact/sales

ok, thx.

**Comment by jensneuse** [comment]
https://linear.app/wundergraph/issue/ENG-1598/export-directive-internal-directive-=-bug
