### ISSUE TITLE
Operations called from internalClient bypass customResolve (and possibly other hooks)

### ISSUE THREAD

**Issue by acdn-sglanzer** [wundergraph/wundergraph#533]
### Bug description

We have two operations using a customResolve.

If the second operation is called externally, the customResolve for the second operation is executed.

If the first operation calls the second operation using internalClient, the customResolve for the second operation is *not* called and instead a normal API call is sent.

### How to reproduce

1. Check out https://github.com/acdn-sglanzer/wundergraph-custom-resolve
2. `npm install && npm start`
3. `curl http://localhost:9991/operations/First`
4. Note that a full list of continents is returned and the logs have `CUSTOM RESOLVE - FIRST` but no `CUSTOM RESOLVE - SECOND`
5. `curl http://localhost:9991/operations/Second`
6. Note that only one mock continent is returned (123/abc) and the logs have `CUSTOM RESOLVE - SECOND`
7. Check `wundergraph.server.ts` and note that both First and Second have `customResolve` hooks and that First is calling Second using the `internalClient`

### Expected behavior

The `customResolve` hook for the Second operation should be called even when the request is executed using the `internalClient`

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```
Version: 0.125.0
Commit: 2cf3db469a0623baa0c1b69ff1bc4b7bf51c4121
Date: 2022-12-31T15:52:49Z
BuiltBy: ci
```

**Comment by Pagebakers** [comment]
I've added it to our backlog for review, thanks for reporting!
