### ISSUE TITLE
Several issues with React Query client

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#544]
### Bug description

Hi, I think I've run into a couple of odd issues when using @wundergraph/react-query, specifically around the useSubscription and useQuery + live configurations.

The react query client appears to try to do a refocus refetch for subscriptions (https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching), and it leads to react query raising an error Missing queryFn (see screenshot). Basically prevents any subscriptions being used at all. Also experience the same issue when using useQuery with enabled: true, live: true.

Also trying to use the onSuccess param with useSubscription leads to an overflow: Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render. eg:
```
const { data, error, isLoading } = useSubscription({
    operationName: "SubscribeAuthors",
    input: {limit: 20},
    // onSuccess: (response: any) => {
    //     console.log("authorSub: successfully established SubscribeAuthors", response)
    // }
})
```

A couple of other small nits:
- You aren't prevented from doing a useSubscription with a live: true param, and it causes another overflow
- The input options seem to always be optional input?:  so typescript doesn't raise an error when an operation requires an input
- You aren't prevented from using a Subscription operation with a useQuery hook, so things crash and burn in the browser when the operation and hook don't align correctly.

![image](https://user-images.githubusercontent.com/7980540/212484029-f5663cbf-624e-4f77-9a4f-30e12bb66d11.png)
![image](https://user-images.githubusercontent.com/7980540/212484037-0fef2449-9607-4498-b47b-f49b3de017c3.png)

### How to reproduce

My setup uses Wundergraph with Hasura as a graphql / subscription provider.

1. Use the React Query client and create a live query using `useQuery`
2. Use the React Query client and create a subscription using `useSubscription`
3. Errors in console?

### Expected behavior

The React Query client should work without raising errors.

### WunderGraph information
[wundergraph.zip.zip](https://github.com/wundergraph/wundergraph/files/10418251/wundergraph.zip.zip)

### Environment & setup

- OS: Windows 11 + WSL2 (Ubuntu) + Docker for Windows + Chrome
- Database: postgres:13.2-alpine
- Node.js version: node:18-alpine

### WunderCtl Version

```
Version: 0.74.7
Commit: 28842cb90ec88189239fdb5770ea24a83f842255
Date: 2022-04-08T13:34:39Z
BuiltBy: ci
```

**Comment by Pagebakers** [comment]
Thanks for reporting this @AesSedai , we're looking into this.

**Comment by AesSedai** [comment]
Ah, the onSuccess / onError useEffect sounds right. Thanks for the feedback.

**Comment by Pagebakers** [comment]
@AesSedai We've published a new release with a couple of fixes for Next/SWR and React Query.

- React Query no longer fetches live queries / subscriptions on window focus
- onSuccess / onError no longer cause infinite loop when they are not memoized.
- input is now required, if there are required inputs.

- You aren't prevented from doing a useSubscription with a live: true param, and it causes another overflow
I'm not sure what you mean with this, useSubscription doesn't have a `live` parameter.

- You aren't prevented from using a Subscription operation with a useQuery hook, so things crash and burn in the browser when the operation and hook don't align correctly.
We need to do more investigation to see what is a proper solution for this. You do get a type error in this case.

**Comment by AesSedai** [comment]
@Pagebakers That's all great news, thank you so much for the update!

Not sure if I can replicate the `useSubscription` + `live` combo, I was going off notes I made when I was this issue and didn't have the exact code sample anymore.

**Comment by Pagebakers** [comment]
Ok thanks! Feel free to open a new issue when you run into it again. 

I've added using a subscription in useQuery crashing the browser to our backlog.
