### ISSUE TITLE
Graphql query not support subscription

### ISSUE THREAD

**Issue by javacode123** [wundergraph/wundergraph#550]
### Bug description

i use subscritpion, bu it not work. just work in rest api

### How to reproduce

1. Go to https://hasura.io/learn/graphql/graphiql to get auth token
2. config subscription
```
subscription {
	hasura_todos(order_by: {id: desc}) {
		id
		title
	}
}
```

4. Run rest api
https://user-images.githubusercontent.com/11720169/212692021-b7425f73-a3da-48dc-9a53-eb0ee2404cdc.png
5. Run graphql api
https://user-images.githubusercontent.com/11720169/212688736-9880583f-2fd3-4f1e-8213-8b20e67dc2ec.png
6. insert todo by hasra
https://user-images.githubusercontent.com/11720169/212689027-d0bfb721-2586-4ccb-abee-743604accefa.png
7. rest api can get push, but graphql api still not work
https://user-images.githubusercontent.com/11720169/212689144-96e2b531-9f8e-42cf-920a-f5f774712b41.png
-->

### WunderGraph information

commit: 556fae1a

### Environment & setup

- OS: macos

### WunderCtl Version

commit: 556fae1a

**Comment by Pagebakers** [comment]
We've investigated this and add this to our backlog, I don't have an ETA yet.
