### ISSUE TITLE
Read limiter on hooks client

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#561]
### Bug description

Opening for tracking, issue reported on discord. 

While I was using a hook (in this case `mutatingPostResolve`) on a subscription with >32kb data, I received the following error in the wundergraph logs:
```
2023-01-16T06:13:18+00:00 INFO: incoming request {"component":"@wundergraph/server","reqId":"d2568427-b791-53b6-dfcd-749bab0006d0","req":{"method":"POST","url":"/operation/CrdtAuthors/mutatingPostResolve","hostname":"localhost:9992","remoteAddress":"127.0.0.1","remotePort":43286}}
response {
  "errors": [
    {
      "message": "unable to resolve",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "failed to read: read limited at 32769 bytes"
    }
  ],
  "data": null
}
```

And this accompanying error in the hasura logs:
```
{"detail":"Unexpected exception raised in websocket. Please report this as a bug: Warp: Client closed connection prematurely","level":"error","timestamp":"2023-01-16T06:13:11.150+0000","type":"unstructured"}
```

### How to reproduce

1. Set up wundergraph with a hook + data source
2. Seed a lot of test data
3. Create a subscription (also maybe query or mutation?) that selects a lot of data

### Expected behavior

There shouldn't be an internal read limiter on the hooks client.

### Environment & setup

- OS: Windows 11 + WSL2 (Ubuntu) + Docker for Windows + Chrome
- Database: postgres:13.2-alpine
- Node.js version: node:18-alpine
- @wundergraph/sdk: "^0.125.0"

### WunderCtl Version

```
Version: 0.74.7
Commit: 28842cb90ec88189239fdb5770ea24a83f842255
Date: 2022-04-08T13:34:39Z
BuiltBy: ci
```

**Comment by fiam** [comment]
Hi @AesSedai. Thanks for letting us know. We fixed this on #564
