### ISSUE TITLE
Unable to execute mutation request with no params

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#562]
### Bug description

When using a Hasura data source, it's possible to remove all rows from a table ([ref](https://hasura.io/docs/latest/mutations/postgres/delete/#delete-all-objects)) like so:
```
mutation {
    delete_authors(where: {}) {
        affected_rows
    }
}
```

When translated to a WG operation like so:
```
mutation {
    hasura_delete_authors(where: {}) {
        affected_rows
    }
}

```
there is an execution error raised in the Hasura logs as follows:
```
{"detail":{"http_info":{"content_encoding":null,"http_version":"HTTP/1.1","ip":"172.18.0.5","method":"POST","status":200,"url":"/v1/graphql"},"operation":{"error":{"code":"validation-failed","error":"expecting a value for non-nullable variable: \"a\"","path":"$"},"request_id":"e505c3db-493a-1f9e-9cca-007ac1c26b50","request_mode":"error","response_size":100,"uncompressed_response_size":100,"user_vars":{"x-hasura-role":"admin"}},"request_id":"e505c3db-493a-1f9e-9cca-007ac1c26b50"},"level":"error","timestamp":"2023-01-19T05:46:41.902+0000","type":"http-log"}
```
I'm not sure how to inspect the compiled query from the WG side, but there shouldn't be any variables included as far as I know.

I was able to work around this for now by adjusting the `where` clause, this operation does succeed:
```
mutation {
    hasura_delete_authors(where: { id: { _neq: "0" } }) {
        affected_rows
    }
}
```

### How to reproduce

1. Set up wundergraph with a hasura data source
2. Create a mutation operation to try to remove all the rows from a table
3. Call the operation

### Expected behavior

The operation should succeed without errors.

### Environment & setup

- OS: Windows 11 + WSL2 (Ubuntu) + Docker for Windows + Chrome
- Database: postgres:13.2-alpine
- Node.js version: node:18-alpine
- @wundergraph/sdk: "^0.125.0"

### WunderCtl Version

```
Version: 0.74.7
Commit: 28842cb90ec88189239fdb5770ea24a83f842255
Date: 2022-04-08T13:34:39Z
BuiltBy: ci
```

**Comment by YuriBuerov** [comment]
Thanks for the bug report. The fix was released: `@wundergraph/sdk@0.133.0`. We would greatly appreciate any feedback you have.
