### ISSUE TITLE
X-CSRF-Token header is missing due to mismatch in operationName and OperationMetadata keys

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#581]
### Bug description

In the newest @wundergraph/sdk@0.132.0, I noticed that the `X-CSRF-Token` header is no longer present in the requests, causing the WunderGraph backend to reject the request.

I think this is due to [this comparison](https://github.com/wundergraph/wundergraph/blob/d7e50cd91d4d18dda7331b348b737ad75a770380/packages/sdk/src/client/client.ts#L242), where the keys in `operationMetadata` no longer match the actual operation names, causing this if condition to always evaluate to false. For example, if I define an operation in `.wundergraph/operations/images/GetImages.graphql`, the `operationName` becomes `images/GetImages` while the key in operationMetadata is `ImagesGetImages`.

### How to reproduce

see above

### WunderGraph information

@wundergraph/sdk@0.132.0

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

wunderctl 0.127.0

**Comment by jensneuse** [comment]
Thanks for reporting. We'll have a look.
