### ISSUE TITLE
Generate static models for TypeScript Operations

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#582]
I have a small suggestion for the generated models of the newly introduced TypeScript Operations. 

Our current project structure looks something like this:

```
└──project
    ├── wundergraph
    │   ├── generated
    │   ├── operations
    │   ├── wundergraph.config.ts
    │   ├── package.json
    │   ├── ...
    ├── frontend
    │   ├── generated
    │   |   ├── client.ts
    │   |   ├── models.ts
    │   ├── package.json
    │   ├── ...
    ├── api_1
    ├── api_2
    ├── ...
```

Up until now, the generated `frontend/generated/models.ts` is self-contained and doesn't need to import anything outside the `frontend` service.

But with the introduction of TypeScript operations, `frontend/generated/models.ts` now needs to import the function definitions from `wundergraph/operations` (see [here](https://github.com/wundergraph/wundergraph/blob/d7e50cd91d4d18dda7331b348b737ad75a770380/packages/sdk/src/codegen/templates/typescript/index.ts#L231)), which in turn imports things from `wundergraph/generated/models.ts`

Although we can make it work, I feel that this is not a very elegant solution as it introduces complex relative imports. It would be better if our `frontend` service doesn't have to import anything directly from our `wundergraph` service. This would involve fully defining the types of TypeScript Operations inside `frontend/generated/models.ts` instead of importing them.

**Comment by jensneuse** [comment]
Are you using Typescript operations or pure GraphQL ops (with or without hooks)?

**Comment by alasdairtran** [comment]
> Are you using Typescript operations or pure GraphQL ops (with or without hooks)?

The new TypeScript operations that you guys recently added. I've been experimenting with them over the weekend. They seem to be a really nice way to write custom logic. But I don't really like the way types are imported in the generated model. For example, our `frontend/generated/models.ts` now contains relative imports such as

```
import type function_GetUsers from "../../../wundergraph/src/operations/GetUsers";
```

which is importing a type from outside our `frontend` service.

**Comment by jensneuse** [comment]
Yes, that's actually on purpose for a reason. If we're doing it like this, the frontend code gets updates to the types even without saving, and you can also refactor types across the frontend and backend. That said, I get your point and I actually planned a feature already to generate self-contained code for the frontend. This is important if we want to publish the types as an npm package for example. In this case, the operations code wouldn't exist.

So, to create self-contained models, we need to extract TS types from the TS operations definitions and generate them as static models, which is technically possible. Once done, we can export different typescript templates, or add options to the typescript templates to make them use type inference (currently only supported) or statically generated types.

Static types would not have the same snappy DX during development, but they would be statically generated, which comes with other advantages.

It could be interesting, e.g. to use type inference during dev (wunderctl up), and static types when running a build that should be exported (wunderctl generate), but I haven't figured out the details yet.

After all, I wanted to ship TS Operations ASAP to get feedback to see what's important.

Let me know what you think about offering options or two approaches. Do you actually like the type inference approach?

**Comment by alasdairtran** [comment]
Thanks for the detailed explanation, Jens. The speed advantage makes sense.

Offering options would be good. I probably would still prefer having static types for everything. In our project, we don't change the API code as often as we change the frontend code, so we wouldn't mind waiting for a bit for the types to propagate after each change. I guess static types are also the only option if we want to build a client generator for other languages (e.g., Golang, Python, Java).

**Comment by jensneuse** [comment]
Yes, you're right. I f we want to support other languages, we need static types.

**Comment by Pagebakers** [comment]
We won't implement generatic static types for TypeScript operation for the moment, but we just released a new guide how you can generate a bundle with static types using tsup which you might find helpful.

https://docs.wundergraph.com/docs/guides/publish-generated-client-to-npm
