### ISSUE TITLE
🐛 BUG: CWA does not work

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [wundergraph/wundergraph#593]
### Bug description

```
❯ npx create-wundergraph-app my-project -E nextjs
'create-wundergraph-app' is not recognized as an internal or external command,
operable program or batch file.
```

```
❯ npm init wundergraph-app my-fed -E apollo-federation
Need to install the following packages:
  create-wundergraph-app@0.3.0
Ok to proceed? (y) y

✔ Created the directory... my-fed
✖ Project creation failed
npm ERR! code 1
npm ERR! path 
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-wundergraph-app my-fed apollo-federation

npm ERR! A complete log of this run can be found in:
```

### How to reproduce

`npx create-wundergraph-app my-project -E nextjs`

`npm init wundergraph-app my-fed -E apollo-federation`

### Expected behavior

Scaffolded app in target folder

### WunderGraph information

null

### Environment & setup

- OS: Windows
- Go version: go1.19.5 windows/amd64
- Node.js version: 16.14.2

### WunderCtl Version

null

**Comment by jensneuse** [comment]
Thank you for reporting, we'll have a look.

**Comment by sschneider-ihre-pvs** [comment]
I have no idea.

**Comment by Aenimus** [comment]
> I have no idea.

Hi again,

I am sure you can appreciate that if we're unable to replicate, it's very difficult to solve an issue like this. My success would suggest the problem lies somewhere within your environment or setup.

What does `npx -v` yield?

**Comment by fiam** [comment]
This looks like a problem in your local setup. Please, let us if you think that's not the case. Closing due to lack of new information in the meantime.
