### ISSUE TITLE
Race conditions caused by accidental sharing client context among internal requests

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#594]
### Bug description

Sometimes, the header of an internal operation is not being forwarded properly. This leads to intermittent request failures in our own app's end-to-end testing in CI. It's a bit difficult to come up with a reproducible example since the bug is indeterministic.

After a bit of digging, I think I might know the cause. In [this line](https://github.com/wundergraph/wundergraph/blob/7bb9b9f2e63d241662eecb690dc0a7fd3f411af0/packages/sdk/src/server/internal-client.ts#L119), `Object.create` is inheriting the context from `baseOperations`. Thus we end up accidentally sharing `client.context` among all internal requests. This means that if we have two requests being made concurrently to two different backends, each requiring a different header, the wrong header might be sent to a backend.

If I change [that Object.create](https://github.com/wundergraph/wundergraph/blob/7bb9b9f2e63d241662eecb690dc0a7fd3f411af0/packages/sdk/src/server/internal-client.ts#L119) to explicitly creating new objects:

```js
const client = {
    context: { clientRequest, extraHeaders },
    queries: { ...baseOperations.queries },
    mutations: { ...baseOperations.mutations },
};
client.queries.context = client.context;
client.mutations.context = client.context;
```

then our CI pipeline no longer fails intermittently. Btw those last two lines ensure that `this.context` is bound to the correct context [here](https://github.com/wundergraph/wundergraph/blob/7bb9b9f2e63d241662eecb690dc0a7fd3f411af0/packages/sdk/src/server/internal-client.ts#L63). Looks a bit hacky though - maybe you guys have better ideas.

### How to reproduce

See above

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by fiam** [comment]
Hello @alasdairtran - We've decided to not fix this one because the internal client is now deprecated. You should use the `operations` instead. Please, check this for an example https://github.com/wundergraph/wundergraph/blob/6abfbf6b5766b8840a39f6f96593ee6e8efc05dd/packages/testsuite/apps/basic/.wundergraph/operations/functions/CountryWeatherViaInternal.ts#L8 - Thanks!

**Comment by alasdairtran** [comment]
@fiam Thanks for the update. I tried migrating `internalClient` to `operations` but it seems that the feature is not quite ready yet. For example, I converted

```js
  const { data: userData } = await internalClient.mutations.InternalUpsertUser({
      input: {
        user: {
          open_id: user.userId,
          name,
          username,
          nickname: user.nickName,
          email: user.email,
          email_verified: user.emailVerified,
          avatar: user.picture,
        },
        update_columns: [
          'name',
          'nickname',
          'email',
          'email_verified',
          'avatar',
        ],
      },
    });
```

to 

```js
    const { data: userData } = await operations.mutate({
      operationName: 'internal/UpsertUser',
      input: {
        user: {
          open_id: user.userId,
          name,
          username,
          nickname: user.nickName,
          email: user.email,
          email_verified: user.emailVerified,
          avatar: user.picture,
        },
        update_columns: [
          'name',
          'nickname',
          'email',
          'email_verified',
          'avatar',
        ],
      },
    });
```

but my Hasura backend now receives the mutation with no input variables (i.e. as if `input` is `null`).

I tried to debug it and found that although the variables are included in the body when the request is sent to `http://0.0.0.0:9993/operations/internal/UpsertUser`, it was somehow lost when Hasura receives the mutation. But I'm not familiar enough with the WunderGraph code base to figure out what happens in between. Do you know how I can debug this further?

**Comment by fiam** [comment]
@alasdairtran That's definitely unexpected and we want to fix that. Could you please open an issue for that bug in the `operationsClient`? If you could attach a repro that would be awesome. Thanks!
