### ISSUE TITLE
Light theme not applying to the whole website

### ISSUE THREAD

**Issue by rohinish404** [wundergraph/wundergraph#598]
### Bug description

The light theme is not getting applied to the whole, portion below Loved by Community including the footer is still dark.
<img width="1435" alt="Screenshot 2023-01-25 at 6 58 55 PM" src="https://user-images.githubusercontent.com/92542124/214576159-a23c9ded-1bbb-4a0e-b81e-a026cf8505b5.png">

### Expected behavior

The light theme should get applied to the whole website.

### Environment & setup

- OS: MacOs
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by Aenimus** [comment]
Hi @rohinish404,

This footer is dark by design; it is not intended to be affected by the light mode setting.

We appreciate your pointing out, and we'll have internal discussion about how to make this intention more clear.

Thanks again.
