### ISSUE TITLE
why do you use Kafka

### ISSUE THREAD

**Issue by HoangNgo88** [wundergraph/wundergraph#606]
Hi, I am reading your project and I love this project
I have a question, why do you choose Kafka in your project instead of others like RabbitMQ or ZeroMQ, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose Kafka instead of others like RabbitMQ or ZeroMQ

**Comment by jensneuse** [comment]
Kafka was chosen for popularity amongst enterprise companies. We definitely want to support other message-oriented middlewares / messages brokers and streaming platforms like the ones you've mentioned.
