### ISSUE TITLE
Document Wundgergraph and Prisma Data Proxy

### ISSUE THREAD

**Issue by jozef-slezak** [wundergraph/wundergraph#610]
Could you document how to run wundergraph in cloudflare workers using prisma data proxy?

Run wundergraph on the edge using prisma data proxy https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-cloudflare-workers

**Comment by fiam** [comment]
Hi @jozef-slezak. It's not possible to run WunderGraph inside a Cloudflare worker for the moment because part of our runtime uses Go.
