### ISSUE TITLE
Support compilation of generated client with pnpm

### ISSUE THREAD

**Issue by andcan** [wundergraph/wundergraph#615]
## Problem

I'm trying to build the generated client as a package to be consumed from a web app.
The problem is that when trying to compile tsc fails with the following error:
```js
// $ tsc
.wundergraph/generated/wundergraph.factory.ts:7:14 - error TS2742: The inferred type of 'createOperation' cannot be named without a reference to '../../common/temp/node_modules/.pnpm/zod@3.20.2/node_modules/zod'. This is likely not portable. A type annotation is necessary.

7 export const createOperation = createOperationFactory<InternalClient, Role>();
               ~~~~~~~~~~~~~~~

.wundergraph/generated/wundergraph.factory.ts:7:14 - error TS4023: Exported variable 'createOperation' has or is using name 'LiveQueryConfig' from external module "/workspace/node/common/temp/node_modules/.pnpm/@wundergraph+sdk@0.132.1/node_modules/@wundergraph/sdk/dist/operations/operations" but cannot be named.

7 export const createOperation = createOperationFactory<InternalClient, Role>();
               ~~~~~~~~~~~~~~~
```
The zod error can be solved by adding zod to types in tsconfig:
```json
{
  "compilerOptions": {
    "types": ["node", "zod"]
}
```
The second error can't be solved because `LiveQueryConfig` is not exported. The problem is solved by modifying `operations.d.ts`: 
```ts
export interface LiveQueryConfig {
    enable: boolean;
    pollingIntervalSeconds: number;
}
```

## Suggested solution

Export `LiveQueryConfig`.

## Alternatives

Generate self-contained TypeScript models for TypeScript Operations (#582).

## Additional context

The problem occurs only when using `pnpm`.

```
Version: 0.127.1
Commit: 1dedf4e05e99f5040715a9792ee63c451c8db0c6
Date: 2023-01-23T10:11:51Z
BuiltBy: ci
```

**Comment by Pagebakers** [comment]
@andcan We released a fix for the LiveQueryConfig issue.

We don't have a plug and play solution for the zod error yet (it happens with pnpm and the nextjs client and swr too).

Setting `"preserveSymlinks": true` in tsconfig resolves it.

**Comment by andcan** [comment]
Thank you for the quick fix!  Unfortunately I'm using [rush](https://rushjs.io/), and it does not play well with `preserveSymlinks`. I'll keep `zod` in types for now.

**Comment by andcan** [comment]
I think this is still relevant.

**Comment by jensneuse** [comment]
> I think this is still relevant.

I agree. Bumping internally.

**Comment by Pagebakers** [comment]
@andcan adding zod to types is still requirement, but other than that it should work. I set up an example bundling the client using tsup:

https://github.com/wundergraph/publish-client

**Comment by andcan** [comment]
Thank you! I'll try asap.
