### ISSUE TITLE
Undefined optional parameters in POST operation are passed to downstream operation as nulls.

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#634]
### Bug description

Related to #114, but the opposite direction...

I had the below operation defined that I'm pretty sure was working when I wrote it (July 2022) but now it is not. The reason is that any parameters that are not passed to the operation (such as if I omitted "description") are passed through to the downstream operation with the value null.

This breaks the semantic that a null value clears a value, but not sending a value leaves it unchanged.

The current behaviour of Wundergraph changes the meaning of the request between client and downstream. Undefined means I have nothing to say about it, null means I definitely don't want a value.

```
# Whichever arguments to the mutation are missing in the body will not be used.
# Any arguments set to null will clear an existing value from the system object.
mutation updateObject($id: Int!, $name: String, $description: String, $icon: URL) {
    object: downstreamUpdateObject(id: $id, name: $name, description: $description, icon: $icon)
    {
        id
    }
}
```
Log Output
```

--- ClientRequest start ---

POST /operations/UpdateObject HTTP/1.1
Host: localhost:9991
Accept: */*
Content-Length: 25
Content-Type: application/json
User-Agent: curl/7.68.0

{"id": 0, "name": "root"}



--- ClientRequest end ---



--- DebugTransport ---

Request:

POST / HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: application/json
X-Request-Id: 3c5a8ca8-cab3-7d7b-513f-28fdc058694e

{"variables":{"description":null,"icon":null,"id":0,"name":"root"},"query":"mutation($description: String, $icon: URL, $id: Int!, $name: String){object: updateObject(description: $description, icon: $icon, id: $id, name: $name){id}}"}

Duration: 38 ms

Response:

HTTP/1.1 200 OK
Content-Length: 28
Content-Type: application/json
Date: Thu, 02 Feb 2023 11:47:52 GMT
Server: uvicorn

{"data":{"object":{"id":0}}}

--- DebugTransport
```

### How to reproduce

- Create a mutation operation on Wundergraph with multiple optional parameters that is a simple forwarding operation to an downstream graphql api with the same signature.
- call the Wundergraph operation with some parameters undefined
- the downstream API will receive the call with the undefined parameters defined with the value 'null'

### Expected behavior

When a Wundergraph operation with optional parameters is called, and one or more of the optional parameters is excluded from the call, then the call that Wundergraph makes to the downstream operation should not have the optional parameters included. They should be absent from the call to the downstream operation.

### WunderGraph information

```
"dependencies": {
    "@types/node": "^14.14.37",
    "@wundergraph/sdk": "^0.133.0",
    "graphql": "^16.3.0",
    "node-fetch": "2",
    "tslint": "^6.1.3",
    "typescript": "^4.7.4"
  },
  "devDependencies": {
    "@types/json-schema": "^7.0.11",
    "@types/node-fetch": "^2.6.1",
    "@wundergraph/wunderctl": "^0.128.0"
  },
```

### Environment & setup

- OS: Mint 20.3
- Go version: 1.13.8
- Node.js version: v18.12.1

### WunderCtl Version

```
Version: 0.128.0
Commit: f136eb833ed444af70a3dd0f6e5d5b4d1b959335
Date: 2023-01-30T12:55:12Z
BuiltBy: ci
```

**Comment by YuriBuerov** [comment]
Hi @greemo, If I understood your question correctly, in this case, you can use `@removeNullVariables` directive. You can check this doc: https://docs.wundergraph.com/docs/directives-reference/remove-null-variables-directive

**Comment by greemo** [comment]
Thanks for the quick response @YuriBuerov , but this case is slightly different. I do not want nulls forcefully removed (as would be done with `@removeNullVariables`, I just don't want them artificially added.
I want the request that I make passed through to the downstream API as I made it to Wundergraph.

If the client passes nulls to the Wu dergraph operation, I want them passed to the downstream API. If the client omits a parameter, I want the parameter omitted on the call to the downstream API.

**Comment by spetrunin** [comment]
Hi, @greemo, as you have added variables to the query we need to somehow process them, graphql spec does not specify the difference between undefined and null, as GraphQL servers implemented in other languages' situation could be different, e.g null, will be only `nil` or `null`. Nullable means the value could be null in a JSON
This means that we could not stick with the only javascript backend implementation

For now to achieve partial updates you could create multiple queries with and without a directive to remove variables

**Comment by greemo** [comment]
Hi @spetrunin, thanks for the quick response. The graphql spec states that explicitly providing a null value, and not providing a value at all are similar, but different cases, and may be interpreted differently by an implementation. That's exactly what I've done, and what is the norm in graphql APIs.

https://spec.graphql.org/draft/#NullValue

**Comment by jensneuse** [comment]
@spetrunin I think it makes sense. Are we able to distinguish between null and omitted?

**Comment by spetrunin** [comment]
Hi @greemo 
We will release a new version today, which will include this fix

please let us know if it works for you

thanks a lot for your contributions!

**Comment by greemo** [comment]
Thanks guys, it works great!
