### ISSUE TITLE
Internal operation API paths are no longer correct in SDK

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#645]
### Bug description

#595 updated the `apiPath` of internal operations in the WunderGraph server (see [here](https://github.com/wundergraph/wundergraph/blob/f2e1ec10f4ab89f6caf4cc713eab18c345aeaddf/pkg/apihandler/apihandler.go#L447)). E.g. if we define a query in `.wundergraph/operations/images/GetImages.graphql`, then the path is now `http://localhost:9991/internal/operations/images/GetImages` instead of `http://localhost:9991/internal/operations/ImagesGetImages`).

However, the SDK is still using the old path (see [here](https://github.com/wundergraph/wundergraph/blob/f2e1ec10f4ab89f6caf4cc713eab18c345aeaddf/packages/sdk/src/server/internal-client.ts#L96)). This means that all calls to internal operations in subdirectories of `operations` now return a 404 error.

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by jensneuse** [comment]
Hey, thank you for reporting. You're right.
We'll provide a fix soon.
