### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by AesSedai** [wundergraph/wundergraph#674]
## Problem
There's a couple of issues with the new docs.
- [This](https://docs.wundergraph.com/docs/features/authentication-aware-data-fetching) doc has a link to the `Getting Started Guide` at the bottom that is currently broken (points to [here](https://docs.wundergraph.com/getting-started)_
- [This](https://docs.wundergraph.com/docs/features/authorization-role-based-access-control-rbac) doc has a link to `configure authorization` at the bottom that is currently broken (points to [here](https://docs.wundergraph.com/docs/guides/configure-authorization))
- [This](https://docs.wundergraph.com/docs/getting-started/vite-quickstart) doc has a link to `1-minute quickstart` in the "#Configure Wundergraph" section that is currently broken (points to [here](https://docs.wundergraph.com/docs/quickstart)), and under the "#What's Next?" section the links for Authentication, Realtime, and File Storage are broken (but Databases works)
- There's also a small issue where if you hover the mouse between the `<-` and `All docs` on the left sidebar, you can cause it to flicker rapidly. [docs-flicker.webm](https://user-images.githubusercontent.com/7980540/218828418-6c7287a5-4246-477c-9b00-3fcc2d4396f1.webm)

There's probably more broken links that I didn't come across, maybe recommend adding a test suite for validating that the links in the docs are valid?

**Comment by Pagebakers** [comment]
Thanks @AesSedai, we're on it!

**Comment by AesSedai** [comment]
Another thing I just saw, I used the search bar to look for `trace` and it returned this page: https://docs.wundergraph.com/docs/legacy/basics-of-time-travel#__next

The lorem ipsum made me chuckle, but it probably shouldn't be surfaced via search since it's a "legacy" doc?
