### ISSUE TITLE
JSON numeric strings converted to numbers

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#684]
### Bug description

Hi All,

Another JSON Scalar handling issue.

In summary, if a graphql API behind Wundergraph returns a string containing only a number, then the string is converted to a number.

Data sent to or from a backing API should not be changed in any way, except when asked.

### How to reproduce

I have been able to create a self-contained wundergraph project to reproduce the error, using the in-built graphql server. It is attached: 
[wgtest.zip](https://github.com/wundergraph/wundergraph/files/10783228/wgtest.zip)

To reproduce:

    install dependencies with yarn
    run with yarn start

Then visit the following URL: http://localhost:9991/operations/Hello

### Expected behavior

The response from the server should be returned to the caller exactly as it is provided from the server.

For the attached project, that is:
{ "data": {"bar": "3345"} }

### WunderGraph information

See attached test server

### Environment & setup

    OS: Mint w/kernel 5.4.0-135-generic
    Go version: go version go1.13.8 linux/amd64
    Node.js version: v18.12.1

### WunderCtl Version

0.131.0

**Comment by jensneuse** [comment]
Seems wrong. Thank you for reporting. We'll have a look.

**Comment by Faizan711** [comment]
is anyone working on this issue, if not i would like to be assigned to it and work on it.

**Comment by jensneuse** [comment]
> is anyone working on this issue, if not i would like to be assigned to it and work on it.

Sounds great. A PR would be welcomed.

**Comment by fiam** [comment]
@Faizan711 We can assign this issue to you if you'd like to work on it. Please, let us know. Thanks!

**Comment by Faizan711** [comment]
i would love to solve this issue, thank you for assigning me. 
I will connect on Discord for issues.

**Comment by fiam** [comment]
> i would love to solve this issue, thank you for assigning me. 
> 
> I will connect on Discord for issues.

Thanks to you. Please, get in touch on Discord and let us know if you need help, we'll be more than happy to assist you.
