### ISSUE TITLE
Schema extension replaces unrelated input fields in Hasura

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#744]
### Bug description

Thanks for looking into #284. I'm currently testing the schema extension in Hasura for replacing the scalar `geography` type. My `wundergraph.config.ts` looks like this:

```ts
const hasura = introspect.graphql({
  id: 'hasura',
  apiNamespace: 'hasura',
  schemaExtension: `
	type CRSProperty {
		name: String!
	}
	type CRS {
		type: String!,
		properties: CRSProperty!
	}
	type Location {
		type: String!,
		crs: CRS!
		coordinates: [Float!]!
	}
	input LocationInput {
		type: String!,
		coordinates: [Float!]!
	}
  `,
  replaceCustomScalarTypeFields: [
    {
      entityName: 'images',
      fieldName: 'location',
      responseTypeReplacement: 'Location',
      inputTypeReplacement: 'LocationInput',
    },
  ],
});
```

The `responseTypeReplacement` works perfectly. But the `inputTypeReplacement` seems a bit too eager and replaces unnecessary fields.

## Correct Replacement

The following input was correctly replaced from

```graphql
scalar hasura_geography

input hasura_images_insert_input {
  id: hasura_uuid
  location: hasura_geography
}
```

to

```graphql
input hasura_images_insert_input {
  id: hasura_uuid
  location: hasura_LocationInput
}
```

## Unnecessary Replacement

But now even this input type

```graphql
input hasura_geography_comparison_exp {
  _cast: hasura_geography_cast_exp
  _eq: hasura_geography
  _gt: hasura_geography
  _gte: hasura_geography
  _in: [hasura_geography!]
  _is_null: Boolean
  _lt: hasura_geography
  _lte: hasura_geography
  _neq: hasura_geography
  _nin: [hasura_geography!]
  _st_d_within: hasura_st_d_within_geography_input
  _st_intersects: hasura_geography
}

input hasura_images_bool_exp {
  _and: [hasura_mages_bool_exp!]
  _not: hasura_images_bool_exp
  _or: [hasura_images_bool_exp!]
  id: hasura_uuid_comparison_exp
  location: hasura_geography_comparison_exp # this is correct
}
```

is replaced with

```graphql
input hasura_images_bool_exp {
  _and: [hasura_images_bool_exp!]
  _not: hasura_images_bool_exp
  _or: [hasura_images_bool_exp!]
  id: hasura_uuid_comparison_exp
  location: hasura_LocationInput # this is now wrong
}
```

which is not what we want. The `location` type here was already correctly typed. 

I'm unsure if this is a bug, or if I miss something in the wundergraph config. Is there a way to tell WunderGraph to replace only the scalar type `hasura_geography` and not touch `hasura_geography_comparison_exp`?

### How to reproduce

.

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by jensneuse** [comment]
Thank you for reporting, adding it to the backlog.

**Comment by jensneuse** [comment]
https://linear.app/wundergraph/issue/ENG-1597/schema-extension-replaces-unrelated-fields

**Comment by Aenimus** [comment]
@alasdairtran Hello!

I'm going to be pushing a fix for this, but the fix will prevent fuzzy matching altogether.

Consequently, you will have to provide the full, exact name of the entity and field to ensure a replacement.

I'll update you when this has been released.

Thank you for reporting!

**Comment by Aenimus** [comment]
@alasdairtran Hello!

Please update your SDK to 0.162.0 where this has been addressed. The merged PR can be found here: https://github.com/wundergraph/wundergraph/pull/1000/files

Please also see the updated documentation:
https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/schema-extension-configuration

The summary is that you know longer need to supply a customJSONScalars array; interfaces are supported; each and every replacement (including inputs must be defined.
