### ISSUE TITLE
Complex GraphQL query arguments not supported

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#747]
### Bug description

Graphql queries are sent via a POST operation, meaning any valid JSON can be used in the query arguments as they are sent in the body of the request.

In Wundergraph, these GraphQL queries are exposed as GET operations, whereby the GraphQL arguments are sent via the query string.

This poses a problem, as it is possible to have GraphQL query arguments that cannot be sent via the converted Wundergraph GET JSON-RPC operation.

In such a situation where query string parameters may not be able to be sent safely via the query string, the convention is to urlencode query parameters before sending, however Wundergraph doesn't seem to do a urldecode before passing the arguments to the operations on the virtual graph.

Without wundergraph doing a urldecode, complex graphql query arguments cannot be safely passed on the GET request as query parameters.

### How to reproduce

{"message":"Bad Request: Invalid input","input":{"refs":"%5B%27my.string%27%5D"},"errors":[{"propertyPath":"/refs","invalidValue":"%5B%27my.string%27%5D","message":"type should be array, got string"}]}

### Expected behavior

- Update documentation to say that all GET requests to the exposed JSON-RPC endpoints must have the query parameters urlencoded
- Wundergraph urldecode all GET query parameters before sending to the operation on the virtual graph.

### WunderGraph information

More info in the rest of these fields is coming... I just wanted to save this before I finish for the night..

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by jensneuse** [comment]
Can you add some more context, e.g. a GraphQL Schema, GraphQL Operation, and the input you're trying to send? Thank you.

**Comment by greemo** [comment]
Hi @jensneuse, I had an issue with my input. I was encoding single quotes in my input rather than double quotes.

Everything is working, sorry for the disturbance. Closing.
