### ISSUE TITLE
wunderctl 0.131.1 broke @transform

### ISSUE THREAD

**Issue by greemo** [wundergraph/wundergraph#769]
### Bug description

Up until and including 0.131.0, the @transform directive with the get operation functioned correctly.

as of 0.131.1 and above, it no longer functions correctly, and is simply ignored.

### WunderGraph information

package.json:
```
{
  "name": "myproj",
  "version": "0.1.0",
  "description": "A wundergraph server",
  "scripts": {
    "dev": "yarn && wunderctl up --debug",
    "start": "cd .wundergraph && wunderctl up",
    "wunderctl": "wunderctl"
  },
  "author": "An Author",
  "license": "SEE LICENSE IN LICENSE.adoc",
  "dependencies": {
    "@types/node": "^18.15.0",
    "@wundergraph/sdk": "^0.141.0",
    "graphql": "^16.6.0",
    "node-fetch": "3.3.1",
    "tslint": "^6.1.3",
    "typescript": "^4.9.5"
  },
  "devDependencies": {
    "@types/json-schema": "^7.0.11",
    "@types/node-fetch": "^2.6.2",
    "@wundergraph/wunderctl": "0.131.0"
  },
  "engines": {
    "npm": "please-use-yarn",
    "yarn": "^1.22.4"
  }
}
```
As soon as I change wunderctl to 0.131.1 or above, the @transform directive stops working.
### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by fiam** [comment]
@greemo Thanks for letting us know. We've reproduced the problem and we're working on a fix. We'll let you know once we have further progress.

**Comment by fiam** [comment]
@greemo We have a fix in place and we'll release it in the next few days. You can track its progress in #774 - Again, thank you so much for your help!

**Comment by greemo** [comment]
Cheers, thanks for the quick response :)
