### ISSUE TITLE
Support for PostgreSQL views

### ISSUE THREAD

**Issue by rnbokade** [wundergraph/wundergraph#775]
Hasura supports postgresql views and stored functions as graphql source same as any table. 
Similar support would be really great addition to the already great set of features.

**Comment by rnbokade** [comment]
I think this could be supported with reference to this https://www.prisma.io/docs/concepts/components/prisma-schema/views
Since as far as I understand wundergraph internally uses prisma.

**Comment by jensneuse** [comment]
This might be possible, yes. We need to check. I'll create a ticket internally and we'll investigate.
Thank you for the input.

**Comment by rnbokade** [comment]
Any update on this?
I tried to go inside the codebase and try to add this myself but was confused as hell. 😅

**Comment by jensneuse** [comment]
Unfortunately we haven't made.progress yet. If you're interested in trying to add views, according to the Prisma team all we need to do is update the Prisma version to a newer one that supports views. So we need to update the Prisma binary Downloader and see if it all works properly. Here's the code where we download binaries: https://github.com/wundergraph/wundergraph/blob/463da5a00246969d5f5bb3df1feee70096d1d963/pkg/datasources/database/engine.go#L337

**Comment by rnbokade** [comment]
So turns out prisma is no longer maintaining their go client.... Damn thats big... Does that means in future wundergraph will have to change it's reliance on it to something else which still works with prisma schemas but without those?

**Comment by jensneuse** [comment]
We're not using the go client. We only used the code to download the binaries, which could be easily changed. All we do is start the Prisma engine as a sub process and talk to it via the http interface. So there's nothing really we need from the go client. The only thing we need to figure out is what's the correct URL to download the latest binaries for different architectures and that's it.
