### ISSUE TITLE
Support token based authentication for SSE subscriptions

### ISSUE THREAD

**Issue by andcan** [wundergraph/wundergraph#810]
## Problem

Subscriptions support token based authentication only if using the fetch based implementation.
Currently I'm deleting `EventSource` from `globalThis` to prevent the client from using `SSE`.

## Suggested solution

I am aware that `EventSource` doesn't support headers, but this should be documented.

## Alternatives

Take in consideration EventSource polyfills which support custom headers.

## Additional context

* [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource/EventSource) 
* [polyfill 1](https://github.com/EventSource/eventsource)
* [polyfill 2](https://github.com/Yaffle/EventSource/)

**Comment by Pagebakers** [comment]
Thanks for reporting @andcan, we will investigate the issue to see how to best handle this case.

**Comment by Pagebakers** [comment]
#857 introduces a new property `sse` that allows you to switch to fetch streaming.

**Comment by Pagebakers** [comment]
@andcan this will be resolved in the next release. We actually fallback to using fetch streaming now if any custom headers are set.
