### ISSUE TITLE
Dependency from generated client to typescript operations

### ISSUE THREAD

**Issue by kevroletin** [wundergraph/wundergraph#819]
### Bug description

@wundergraph/sdk": "^0.143.1"

**Our use case:**

We want to package generated typescript client code as an npm package to share it with a frontend team.

For this to work we prefer to put generated sources outside of .wundergraph directory where we keep our packaging build scripts.

**Problem:**

Generated models.ts had dependency to our typescript operation:

```
// Code generated by wunderctl. DO NOT EDIT.

import type function_GetFile from "../operations/GetFile";
```

As the result:

* generated client can't be placed outside of `.wundergraph` directory. Because GetFile.ts includes other generated files via  relative paths (similarly to examples from documentation):

```
import { z, createOperation, AuthorizationError } from '../generated/wundergraph.factory';
```

* it's not obvious which subset of files needs to be published

---

This is not a critical issue, because we still can figure out how to package generated client. But making packaging of generated client more straightforward is helpful for organizations with separate backend/frontend teams.

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by Pagebakers** [comment]
Thanks for your feedback @kevroletin. It's a great suggestion, I've opened an internal issue to discus this with the team.

**Comment by Pagebakers** [comment]
For reference #582 and #615

**Comment by fiam** [comment]
We now have a guide detailing how to compile an independent package that doesn't depend on the operations https://docs.wundergraph.com/docs/guides/publish-generated-client-to-npm - Closing as completed.
