### ISSUE TITLE
Svelte Example or tutorial app

### ISSUE THREAD

**Issue by Slickstef11** [wundergraph/wundergraph#820]
## Problem

With the new added supported for Svelte, a example application would be helpful.

## Suggested solution

I'd like to see a simple application that uses WunderGraph and Svelte. A full tutorial or documentation would be best so I could follow along nicely. 

## Additional context

Possible projects could be a TODO app or a small blog site.

**Comment by JBic9832** [comment]
Is this what you are looking for?
https://docs.wundergraph.com/docs/getting-started/sveltekit-quickstart
https://docs.wundergraph.com/docs/tutorials/your-first-wundergraph-application

**Comment by Slickstef11** [comment]
@JBic9832 

Thank you for linking those!

I'm creating some easy tickets for new users to be able to pick up and contribute to WunderGraph. 

I'd love to see a small application build with Svelte so we can create a tutorial out of it.

**Comment by N-NeelPatel** [comment]
@Pagebakers - a todo app is already added in the example.
link: https://github.com/wundergraph/wundergraph/tree/main/examples/sveltekit-todos

**Comment by ganeshmani** [comment]
@Slickstef11 Do we still need to create a tutorial app? I would like to work on this issue. Let me know

**Comment by vickywane** [comment]
@Slickstef11 has the Svelte tutorial been created? 

I'll love to take this one up if it hasn't been created. Can you please assign this issue to me?

**Comment by shashtag** [comment]
Hey @Slickstef11,

I don't understand the status of this ticket. It seems you already have a Svelte Example app and also docs for how to integrate wundergraph with svelte.

What is the exit criteria for this ticket?

**Comment by Slickstef11** [comment]
Hey @shashtag sorry I've been OOO. This one can be closed for now. We got some examples.

**Comment by rishi-raj-jain** [comment]
@Slickstef11 Do let me know if you're looking for other framework examples. I can spin one up!

**Comment by rishi-raj-jain** [comment]
Can we close this?
