### ISSUE TITLE
Propagate errors from Upstream REST services to the client

### ISSUE THREAD

**Issue by kevroletin** [wundergraph/wundergraph#822]
This request is based on an older conversation which happened around version "0.138" (before the implementation of openApiV2).

---

The diagram below shows a setup with a Wundergraph-based API gateway and two REST microservices which I'll call "upstream" services.

```
                     |                             +-------------+
                     |                        404  |Microservice1|
+----------+         |          +-----------+ <----+             |
|          |   404              |           |      +-------------+
| Client   | <----------------- | WG        |
|          |         |          |           |      +-------------+
+----------+         |          +-----------+      |Microservice2|
                     |                             |             |
                     |                             +-------------+                 
```

The response code 404 in the diagram demonstrates the idea that an application-specific error generated in the Microservice1 is a "useful" result of an operation which should be somehow propagated to the client.

Our requirements are:
- we want to detect errors from a client (that's possible now)
- we want to distinct between application-specific and system errors (4XX vs 5XX) in the client
- we want to get messages of application-specific errors in the frontend
- we want to get messages of internal server errors in the frontend during the development stage.

---

There are several ways how our HTTP microservices (aka "upstream" services) can fail:
- 4XX statuses - application errors that should have meaningful messages (we want frontend to read those messages)
- 5XX statuses - internal server error; should have clues for debugging (we want the frontend to read those messages during the development phase of the application; in production, we would probably want to replace the actual message with a reference which can be attached to a bug report)

On top of that Wundergraph server might experience difficulties communicating with downstream services in different ways: DNS resolution error, response timeout, and response schema error. Which we probably should treat similarly to 5XX microservices errors.

---

Currently, for 4XX and 5XX errors WG client returns a "null" value and status 200. That way the frontend can understand that there was an error, but there is no additional information about the problem.

**Comment by fiam** [comment]
Hello @kevroletin - Thanks a lot for the detailed requests. We already have some of it working in the latest SDK, but we would like your input deciding how to move forward. Let me elaborate. 

Right now you can define multiple response types, varying by the status code. For example, for an endpoint that might return 200, 400 or 404 you can do something like this:

```yaml

responses:
  '200':
    description: A note object
    content:
      application/json:
        schema:
        type: object
        properties:
          id:
            type: integer
            format: int64
          text:
            type: string
  '400':
    description: The specified note ID is invalid (not a number).
    content:
      text/plain:
        schema:
          type: string 
  '404':
    description: A note with the specified ID was not found.
    content:
      text/plain:
        schema:
          type: string
```

This produces the following GraphQL schema:

```graphql

	 type Query {
	  """Returns a note by ID"""
	  notes_noteByID(
	    """Note unique identifier"""
	    noteID: Int!
	  ): notes_noteByID_response
	}

	type notes_String_container {
	  String: String
	  _join: Query!
	}

	type notes_newNote_200_response {
	  id: Int 
	  _join: Query!
	}

	type notes_noteByID_200_response {
	  id: Int 
	  text: String
	  _join: Query!
	}

	union notes_noteByID_response = notes_String_container | notes_noteByID_200_response
```

This way you can tell apart when the response is successful and when it's not, readying either an object with the response or an error message. Unfortunately, there are some limitations:

- There's no way to tell apart a 400 and a 404, because they use the same response schema
- Transport errors (e.g. network failures) are not handled
- Unexpected status codes are not handled

We would love to have your input on how to proceed with these.

For telling apart different errors with the same schema but different error codes, we're thinking of adding a response type per status code, which would produce the following response types:

```graphql

type notes_noteByID_400_response {
	String: String
	_join: Query!
}

type notes_noteByID_404_response {
	String: String
	_join: Query!
}

type notes_noteByID_200_response {
	id: Int 
	text: String
	_join: Query!
}

union notes_noteByID_response = notes_noteByID_200_response | notes_noteByID_400_response | notes_noteByID_404_response
```

As for handling transport errors and unexpected status codes, we would like the produce the following types:

```graphql
type notes_unexpected_response {
	ResponseCode:  Int!
	Body: String
	_join: Query!
}

type notes_error {
	ErrorCode:  Int!
	Message: String
	_join: Query!
}

union notes_newNote_response = notes_newNote_201_response | notes_unexpected_response | notes_unexpected_response
```

This would allow us to handle both unexpected HTTP status codes without having to define a default response schema, as well as errors originated in the transport layer.

Before we move forward with this proposal, we would like to have your confirmation that this would fit your use case nicely. Please, let us know. Thanks!

**Comment by kevroletin** [comment]
Hi @fiam, thank you for asking and waiting feedback.

---

Our requirements.

We need a client to be able to **distinguish between different status codes**. Currently, in our code, we only need to distinguish between 4XX and 5XX errors. The reason for that is: (4XX codes) backend code which returns 4XX result is running "normally" it didn't crash unexpectedly, and it can return a data structure with additional information about the problem; (5XX codes) many times those are crashes and other unexpected problems, where many times we can't (or don't want) to return any structured information about the error. So at this moment distinguishing between 4XX and 5XX errors with ability to add structured data to 4XX responses is enough.

With 5XX responses there are two additional considerations: 1) for production, we don't want to send error messages to the client, instead, we want to save error messages somewhere and return a reference to that error, so that end users can add the reference to a bug report 2) in case of 4XX responses we want to return structured data in a body of the response; in case of 5XX responses, it always will be a string (because from one side we don't want to handle it on client, from the other side, we are using tons of libraries and middlewares, string will work regardless of what they put in the body of the response).

Distinguishing between individual error codes, for example 400 vs 404 is a good idea because many (probably most) of Rest API use them. And while what I've just said above is enough for us, having a more flexible solution is better. We will have different requirements in the future, having a flexible solution is better.

---

Proposed implementation.

Having a data type per response code seems reasonable to me. Having a defined type with string body for unexpected errors looks good to me as well. This solution will fulfill our requirements.

A few considerations.

It would be great to keep client-side error handling similar in case of GraphQL and TypeScript operations. Client reads TypeScript errors like that
https://docs.wundergraph.com/docs/typescript-operations-reference#custom-error
Consistent error handling for both types of operations would reduce difficulty of a client library.

Since this code is auto generated, it's possible to end up with a "huge" data structure which people wouldn't write manually. I am not familiar with TypeScript compilation performance, just want to bring attention to potential problems.  You probably have enough experience to judge resulting compilation times :)

**Comment by fiam** [comment]
Thanks @kevroletin - As discussed, this is now in progress. We'll keep you updated!
