### ISSUE TITLE
UI for reporting errors in config/operations

### ISSUE THREAD

**Issue by kevroletin** [wundergraph/wundergraph#823]
This issue is based on an older conversation which happened around version 0.138.

## Problem

It's easy to miss certain errors in wundergraph.config.ts. 

## Cause

This happens due to combination of two factors:
* wundergraph keeps going after errors in config and in operations
* errors get log in logs scroll.

The "keep going despite errors" strategy is useful for interactive development (you can edit a .graphql operation and the server will keep going which the operation is half-complete).

However non-trivial config might contain number of operations. Each operation generates a log line "operation registered". As the result errors about skipped operations get lost in log scroll.

In my experience, I don't use interactive development feature because I need to scroll up to check if there are any issues in operations. As the result, I Ctrl+c, Ctrl+l to clean the terminal and then start the server again.

## Suggested solution

I personally, would prefer a cli switch to stop on the first error.

Alternatively, WG team mentioned development of a "terminal UI" to get list of errors.

**Comment by Pagebakers** [comment]
We just released our new TUI in `0.144.1` and love to get your feedback on this.
