### ISSUE TITLE
make doesn't work

### ISSUE THREAD

**Issue by jensneuse** [wundergraph/wundergraph#84]
### Bug description

packages/nextjs-testapp build$ pnpm run generate && next build
[1 lines collapsed]
│ > @test/nextjs-starter@0.1.0 generate /Users/jens/repos/wundergraph/packages/nextjs-testapp
│ > cd .wundergraph && wunderctl generate
│ Error: could not find file or directory: base directory "/Users/jens/repos/wundergraph/packages/nextjs-testapp/.wundergraph/.wundergraph" not found

I've had to make this change so that "make" works again:
https://github.com/wundergraph/wundergraph/commit/cff1bf3447f4988fa1f9dcbf1894b81df6434be2

@StarpTech it seems like the changes you've made recently assume that we don't cd into `.wundergraph` because the generated directory is `/nextjs-testapp/.wundergraph/.wundergraph`. Maybe you missed to check for that case?

### How to reproduce

run make

### Expected behavior

x

### WunderGraph information

x

### Environment & setup

x

### WunderCtl Version

latest

**Comment by StarpTech** [comment]
Addressed in https://github.com/wundergraph/wundergraph/commit/2f4ed274bba67c2ddf3ff37c19fa27f10a26bbe5. I will make a release shortly.
