### ISSUE TITLE
customJSONScalars have no effect on Response data fields

### ISSUE THREAD

**Issue by alasdairtran** [wundergraph/wundergraph#846]
### Bug description

The `customJSONScalars` works perfectly for input fields, but it doesn't update the types in response data.

I think it's because of [this line](https://github.com/wundergraph/wundergraph/blob/96572ca9440d679f7538d93df1bd81b4d3f97f01/packages/sdk/src/graphql/operations.ts#L1356), where we always return a string type if we see scalar type. I guess the fix would be to add an extra condition before it and return an empty object if `fieldType.name.value` is defined in the `customJSONScalars` array.

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by Aenimus** [comment]
Hello @alasdairtran,

Please could you check this behaviour with wundergraph/sdk version 0.162.0+ and let me know the result?

And if the behaviour still persists, please could you provide instructions for reproduction?

Thank you!

**Comment by greemo** [comment]
I also have this issue. I'm not sure why we even apply a json schema to scalars. By definition, they are supposed to be schema-free right? Or at least schema-opaque to GraphQL

**Comment by greemo** [comment]
See also previous detail issue: https://github.com/wundergraph/wundergraph/issues/806

**Comment by alasdairtran** [comment]
Hi @Aenimus, unfortunately, the new changes don't really work and the deprecation of `customJSONScalars` prevents us from upgrading. We currently have to pin our WunderGraph SDK to v0.161.0.

As @greemo mentioned, a lot of the time, we don't know the exact type of the jsonb objects stored in our database. We have hundreds of jsonb attributes scattered across our schema. In version v0.161.0 and earlier, we were able to tell WunderGraph: "Type all hasura_jsonb as opaque JSON" using `customJSONScalars`. Now this is no longer possible and all `hasura_jsonb` are always typed as `string`.

Here's a concrete example - a simplified type from our Hasura database:

```graphql
type hasura_mochi_messages {
  author_id: hasura_uuid!
  content(
    "JSON select path"
    path: String
  ): hasura_jsonb!
  id: hasura_uuid!
}
```

By default, WunderGraph will type `content` string. For example, this is the default generated typescript model given by WunderGraph:

```typescript
export interface hasura_mochi_messages_insert_input {
	author_id?: string;
	content?: string;
        id?: string;
}
```

which is not correct. However in v1.161.0 and earlier, if we include `hasura_jsonb` in `customJSONScalars`, WunderGraph was able to type `content` correctly, that is:

```typescript
export type JSONValue = string | number | boolean | JSONObject | Array<JSONValue>;

export interface hasura_mochi_messages_insert_input {
	author_id?: string;
	content?: JSONValue;
        id?: string;
}
```

My question is: How can we achieve the above in v1.162.0 and later?

**Comment by Aenimus** [comment]
Hi @alasdairtran,

Could you elaborate on what's not working? It'd be easiest if you could send me a direct message through [our Discord guild](https://discord.com/invite/Jjmc8TC). You'll find me as David@WunderGraph (username Aenimus).

However, you can still do this with `customJSONScalars`. It's just that now you must be specific on the types you're changing. The previous implementation would change types you didn't want to be changed (see your original issue https://github.com/wundergraph/wundergraph/issues/744).

**Comment by Aenimus** [comment]
@greemo @alasdairtran `customJSONScalars` has been reimplemented and should work for both input and response types.

Thank you for reporting!
