### ISSUE TITLE
Subscription feature on iOS. 

### ISSUE THREAD

**Issue by tiwariammit** [wundergraph/wundergraph#887]
## Problem

Hi Actually, My company is using Wundergraph. We have chat feature in application. I want to obtain feature like socket

## Suggested solution

I can do by using API, but it will too slow, and problem is that I don't know when there is new message arrived, so I want to observe the event like socket. Is there anyway that I can achieve observer in Swift. Currently, I am using URLSession, and swift. Can you please suggest me a best way to solve my issue?

**Comment by tiwariammit** [comment]
Currently, My company is using WunderGraph, So I using using API to get response from server, but we have chat feature as well, which is a bit hard using API hit (one way handshaking), I want to do like two way handshaking, make an observer, which observe and trigger my app method if any changes in server.

**Comment by jensneuse** [comment]
> Is there any example how to used subscription api in Swift, iOS?

Currently not. It would need to follow the rules of the RPC Protocol:
https://docs.wundergraph.com/docs/architecture/wundergraph-rpc-protocol-explained#streaming-responses-subscriptions-and-live-queries
