### ISSUE TITLE
@wundergraph/wunderctl 0.144.0 not found from npm

### ISSUE THREAD

**Issue by MarkJPerry** [wundergraph/wundergraph#889]
### Bug description

Using version 0.147.0 of @wundergraph/sdk fails to install as it has a dependency on @wundergraph/wunderctl 0.144.0 which does not exist on npm. 

Error: No matching version found for @wundergraph/wunderctl@^0.144.

### How to reproduce

npm i @wundergraph/sdk@0.147.0

### WunderGraph information

None

### Environment & setup

All

### WunderCtl Version

0.144.0

**Comment by MarkJPerry** [comment]
Looks like this might have just been sorted:
https://www.npmjs.com/package/@wundergraph/wunderctl?activeTab=versions

**Comment by Pagebakers** [comment]
Thanks for opening the issue.

There was an issue in the release, it's been resolved.
