### ISSUE TITLE
Add support for Fauna Region Groups

### ISSUE THREAD

**Issue by faunaee** [wundergraph/wundergraph#94]
## Problem

The steps to use Fauna as a data store do work, but only the Classic Region Group works because the Fauna GraphQL API endpoint URL is a static value. To support Region Groups, the endpoint URL needs to be configurable.

## Suggested solution

I started a PR in my own fork: https://github.com/faunaee/wundergraph/pull/1

I didn't create the PR in this repo because I was unable to get `make test` to complete successfully. Details in my PR description.

**Comment by jensneuse** [comment]
merged
