### ISSUE TITLE
Wildcard CORS does not work

### ISSUE THREAD

**Issue by rwest202** [wundergraph/wundergraph#95]
### Bug description

The CorsConfiguration type recommends to use `['*']` as the value to all origins. However when I set the wildcard values I continue to get cors issues. Setting the domains manually works fine, but any wildcards in the domain seems not to work at all.

```
export interface CorsConfiguration {
    /**
     * AllowedOrigins is a list of origins a cross-domain request can be executed from.
     * If the special "*" value is present in the list, all origins will be allowed.
     * An origin may contain a wildcard (*) to replace 0 or more characters
     * (i.e.: http://*.domain.com). Usage of wildcards implies a small performance penalty.
     * Only one wildcard can be used per origin.
     * Default value is ["*"]
     */
    allowedOrigins: ConfigurationVariable[];
```

### How to reproduce

1. Go to 'wundergraph.config.ts'
2. Change 'allowedOrigins to `['*']`
3. Run
4. See error when loading data from any origin

### Expected behavior

CORS allows all origins

### WunderGraph information

```
cors: {
    ...cors.allowAll,
    allowedOrigins: ['*']
}
```

### Environment & setup

- OS: Windows, deployed to Ubuntu in production

### WunderCtl Version

```
0.94.2
```

**Comment by YuriBuerov** [comment]
We were trying to replicate this issue on wunderctl ```0.100.0```, and seems it works fine. Please reopen this issue if you see it again.
